src/components/pages/authentication/social/FacebookButton.js
Relates to https://github.com/big-neon/bn-api/pull/218
Tested it locally and was able to authorize the email permission and login while in the associated branch for the API.
=> Add email scope to facebook login

src/components/pages/events/CheckoutSuccess.js
Closes #1270 
Just updates the wording for after a successful checkout:
=> Wording updates on success page

.githooks/pre-push
A pre-push githook that will prompt you if you are pushing to the `live` branch to prevent accidental pushes that will get deployed.
Make sure you are using the project hooks path
`git config --set core.hooksPath .githooks`
=> Protect the live branch

src/components/pages/admin/events/dashboard/codes/CodeDialog.js, src/components/pages/admin/events/dashboard/codes/List.js
This fixes the following issues:
- The availability was not being calculated correctly for the list of codes in the event dashboard table
- The max_per_user field was not being saved or populated in the admin dialog
Requires https://github.com/big-neon/bn-api/pull/1181
=> Fixes for max_per_user and availability count issues for discount codes

src/components/pages/events/TicketSelection.js
Fix an error where cents were not formatted as dollars.
=> Format cents as dollars

src/components/pages/boxoffice/sales/Index.js, src/stores/boxOffice.js
Closes https://github.com/big-neon/bigneon/issues/69
In the box office if you had a hold on a ticket type marked as private it wouldn't show the bottom checkout bar AND if you added tickets from that hold to the cart it would crash the box office.
=> Fix Box Office bug when adding holds for private ticket types

src/stores/eventUpdate.js
Closes: #1350
The associated issue detailed a bug where the default ticket type start date was always set to 12:30 PM PDT. The goal was to have this date be instead set to 'Now' as the 12:30 was a bit random. I have it use the beginning of the current hour and convert it to PDT (since moment uses the local timezone and the web form is PDT labeled).
Note: This change also affects the unpublished events but it's the same behavior as it used to be just with the current date set in place of 12:30 PM PDT that day. We force a start_date for any ticket type that isn't the parent to other ones so a date is currently required by the backend even for ticket types belonging to unpublished events (we could always change this in the future though).
Not sure if the beginning of the hour is ideal so can …
=> Default ticket type start date to start of hour

src/components/pages/admin/events/List.js
Closes: #1373 
The inventory held count on the dashboard is incorrect. We provide two numbers via the API the quantity of the total held inventory and the quantity of sold held inventory. Previously the logic always displayed the total held inventory regardless of quantity sold. 
DB values showing total, unsold, and sold quantities:
Ticket types listing showing correct value:
Before modification:
After modification:
* No change
=> Event Dashboard: Fix held inventory count displayed

src/components/pages/admin/events/updateSections/Details.js
Closes: #1389 
Relates to: #1411
Further adjustments to this logic to auto select if there is only 1 private venue available. In the original pull request I mentioned how we'd only be able to use this up until we made some public venues as the issue mentioned selecting it if only one was available. @Krakaw mentioned in that PR that we could still use this logic for organizations that have only one private venue. I've adjusted the logic here in place of checking for only one available venue to check for only one private venue per that comment. 
Added Keith for review just to make sure that was the intent here but makes sense especially for smaller organizations.
* No change
=> Event Create: Auto select venue if only 1 private available

src/helpers/downloadCSV.js
Closes: #1441
This pull request closes the associated issue by changing the way we handle CSVs in the app to use blobs. Previously the app would fail with a network error for larger datasets (I experienced it locally with a dataset of 116800 rows) but after the fix I no longer see that issue.
I tested this by using Mike's PR (https://github.com/big-neon/bn-api/pull/1275) which introduces a new mocha test that bulk creates orders. Unfortunately it uses Stripe so it's rather slow so I stopped it midway through and instead edited the `src/helpers/downloadCSV.js` file to loop over the rows it adds 800 additional times creating a massive CSV.
* No change
=> Fix issue with download CSV and large datasets

src/helpers/downloadCSV.js
Closes #1468
Fixes a mistake I introduced with #1441 that I missed while testing given I was using dummy data to create a larger CSV. The line was needed with the old approach but is included in the CSV itself with the new.
* No change
=> Fix issue with CSV export including invalid row

src/components/pages/boxoffice/guests/Index.js
Closes: #1473
The associated issue mentioned how the guest list search for the web was not working for the full name. It appears that it does not hit the API using the query but instead does a local search. Guessing this is being done for speed purposes? I tried locally to switch to use the API instead but it really slowed the app down considerably. May be something we want to iterate on and just make this temp change to append the full name to the list of search criteria. 
@Jasonvdb just a heads up re: the API query not in use here. Edit: filed #1479
* No change
=> Search guest list by full name

src/components/pages/admin/reports/eventSummaryAudit/SummaryAudit.js
Closes: #1471 
Related to / needs: https://github.com/big-neon/bn-api/pull/1286
This pull request removes a temp fix that was in place for grouping the event summary audit report by the ticket pricing name, price in favor of the api doing it directly.
Note below the total face being wrong is known and a fix is ready but waiting on hearing back here before I push it up: https://github.com/big-neon/bn-web/issues/1417
Pre API and web modifications:
With web change but no API change (reverts the temp fix):
With both:
* No change
=> [DNM] Fix multiple row issue for report

src/components/pages/boxoffice/guests/Index.js
References: #1473
This adds support for searching by last name prior to first. It wasn't in the original acceptance criteria for the parent issue https://github.com/big-neon/bigneon/issues/165 but may have value in countries where last name generally is written prior to first like Japan as it may feel more natural to search that way. I also ignore the commas in the search query in case people try to emulate the names written below now that we support last name first.
* No change
=> Adjust search to allow for last name prior to first name

src/components/pages/boxoffice/sales/Index.js
https://github.com/big-neon/bigneon/issues/186
Fixes a crash in the box office for bn-web when a ticket type is unavailable and not visible on the frontend but adding a hold references the price for the missing ticket type.
If we don't receive the ticket type details, rather use the price provided in the hold.
* No change
=> Box office hold crash fix

src/components/pages/admin/events/updateSections/Tickets.js
`saleEndTimeOption` wasn't being set and the default case option was using the ticket type end date (out of view) while it should have been using the event end date.
* No change
=> When `saleEndTimeOption` isn't set, ticket end date is the event end date

src/components/pages/admin/organizations/sections/FeeSchedule.js
Connected to big-neon/bigneon#184
Adds the credit card fee to the overview fee page.
* No change
=> Added a display of the credit card fees for org owners

src/components/pages/myevents/EventTicketsCard.js
Connected to #1638 
When a ticket has been redeemed hide the show qr and transfer actions
* No change
=> Hide actions when a ticket has been redeemed

src/stores/selectedEvent.js
https://github.com/big-neon/bigneon/issues/174#issuecomment-514299045
Just adding timezone to the event time that's displayed
* No change
=> Adding timezone display for event show times on event view page

src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/EventDescriptionBody.js, src/components/pages/events/TicketSelection.js, src/components/pages/events/ViewEvent.js
Connected to big-neon/bigneon#192
If an event is cancelled disable purchase buttons and add a link back to the home page.
* No change
=> Added checks and displays for cancelled events

src/components/pages/admin/fans/FanActivityCardRow.js
Date was looking like this:
This PR makes it like this for this screen width:
* No change
=> Added break point to adjust flex value so date doesn't wrap to new line

src/components/common/cart/CartHeaderLink.js
https://app.asana.com/0/1135145228458502/1133349072898517
If you have navigated to another event the cart would incorrectly take you back to that event when clicking on the cart icon in the menu. This PR uses the event_id in the items list from the cart response to navigate to the correct `events/tickets/confirmation` page
http://cl.ly/744c807db250
* No change
Requires big-neon/bn-api#1454
=> Return to the correct event when clicking on the cart

src/components/pages/events/CheckoutSelection.js, src/components/pages/events/TicketSelection.js
https://app.asana.com/0/1135145228458502/1133349072898527
New rules for auto selecting a ticket quantity when there is only one ticket type:
- If the default auto select amount is NOT divisible by the increment amount, rather auto select the first increment.
- If `limit_per_person` is set don't allow auto selecting more than the user is allowed to buy
- If `available` < `increment` don't auto select any.
* No change
=> Auto add quantity rules

src/stores/selectedEvent.js
Fixes a bug causing an event to show no tickets available if the last ticket type checked wasn't available.
* No change
=> hasTickets should be true if at least one ticket type is available

src/components/pages/admin/events/dashboard/orders/order/Index.js, src/components/pages/admin/events/dashboard/orders/order/TicketCard.js
https://github.com/big-neon/bn-web/issues/1687#issuecomment-520484313
Ticket total should be what the user actually paid. 
`total_price_in_cents - fees_price_in_cents + discount_price_in_cents`
* No change
=> Updated ticket total to be face value (total - fees - discount)

src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js, src/components/pages/authentication/social/FacebookButton.js
Requires big-neon/bn-api#1141
Show marketing menu for events that have it in the extra_admin_data field. This will be used for the FB App review team to see preview functionality
* No change
=> Show FB marketing menu for certain events

src/components/pages/events/Meta.js
https://app.asana.com/0/1136728345391137/1139369806323215
Use the slug url instead of the event id
* No change
=> Use the slug url in the metadata

src/components/pages/admin/events/updateSections/Details.js
Blocked by big-neon/bn-api-node#387
https://app.asana.com/0/1136728345391137/1135976069951305
Added `Tech` and `Other` category. Changed event type to event category on the event edit page
* No change
=> Changing event type to event category

src/components/pages/admin/events/dashboard/orders/Index.js, src/components/pages/admin/events/dashboard/orders/OrderRow.js, src/components/pages/admin/events/dashboard/orders/order/Header.js, src/components/pages/admin/events/dashboard/orders/order/Index.js
https://app.asana.com/0/1138868228851596/1139476696018194
https://github.com/big-neon/bn-web/issues/1724
The API tracks box office orders by treating the box office agent as the user_id for the order and the purchased for user as the on_behalf_of_user_id. The orders API reflects this in that it returns a on_behalf_of_user along with the user when there is a box office purchase.
These changes just reflect the box office user in the frontend by using the on_behalf_of_user instead of the user when it's available.
Down the line we may want to refactor the logic so all orders reflect the end purchasing user in the user_id field but that's likely out of scope for the time being.
Existing order purchased via box office for different user:
Purchasing for a new user via box office:
Both orders …
=> Fix box office purchase display

.githooks/pre-commit, src/components/pages/admin/events/dashboard/orders/order/Index.js, src/components/pages/events/ViewEvent.js
https://app.asana.com/0/1138868228851596/1139351286534657
When viewing an order from a direct link it first sets the current org id for the user.
When viewing an event it changes the current org if you are a part of that org.
http://cl.ly/4413d93f9375
* No change
=> Set the organization_id when viewing an order or an event

src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js
https://app.asana.com/0/1138868228851596/1141131926912004
When applicable, use an enum for the event end time. Can override the date by using `Manual` and passing along a set date.
Looks the same but wont try to guess `DoorTime`, `StartTime` or `CloseTime` based on the set time.
No visual changes.
* No change
https://github.com/big-neon/bn-api/pull/1508
https://github.com/big-neon/bn-api-node/pull/391
=> Using an enum for ticket type end date when applicable.

src/components/pages/admin/events/dashboard/orders/order/Index.js
https://app.asana.com/0/1138868228851596/1145552426833993
It was noticed that the price and fees total on the order management page was calculated incorrectly. 
Dug into it and noticed we are taking the total of the order and subtracting fees here:
https://github.com/big-neon/bn-web/blob/bf23da36723cf8a99270a1ea55497e8b83bd2450/src/components/pages/admin/events/dashboard/orders/order/Header.js#L63
But not including the event fee (we include credit card fees twice so guessing it was a typo at the time):
https://github.com/big-neon/bn-web/blob/bd23b77a69a57020b9006e65a1a11dc849753f2c/src/components/pages/admin/events/dashboard/orders/order/Index.js#L142
This just modifies the logic to include the event fee in the fee total which fixes the ticket total as well given that calculation.
Example …
=> Fix fee calculation for orders to include event fee

selenium/qa/Dockerfile, selenium/qa/config/hub/testng.xml, selenium/qa/config/parallel_suite.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/docker-compose.yml, selenium/qa/pom.xml, selenium/qa/src/test/java/config/DriverFactory.java, selenium/qa/src/test/java/config/HubRemoteDriverManager.java, selenium/qa/src/test/java/pages/FacebookLoginPage.java, selenium/qa/src/test/java/pages/LoginPage.java, selenium/qa/src/test/java/pages/admin/organizations/CreateOrganizationPage.java, selenium/qa/src/test/java/pages/components/admin/AddTicketTypeComponent.java, selenium/qa/src/test/java/test/CreateEventWithAdditionalOptionsStepsIT.java, selenium/qa/src/test/resources/conf/beta_test_data.json, selenium/qa/src/test/resources/conf/develop_test_data.json
created new profile in maven to execute tests,  (hub profile)
new execution command is
` mvn clean verify -P hub -Dhuburl=http://hub_host:hub_port/wd/hub -Dbaseurl=base_url`
this will execute `testng.xml` suite file located in` selenium/qa/config/hub/` folder.
Modified docker-compose file a bit. There is no need to start executing tests as separate docker compose service for each browser. That is already handled by testng, through` testng.xml` and files it references That way some degree of parallel execution can be achieved. However if it is a requirement, some modification can be done to do that.
To ensure that tests base code is updated each time the docker-compose is run, and tear down of containers was not executed from previous runs. We can run
`docker-compose -f <file_name> up …
=> automated tests in docker

src/components/pages/admin/reports/boxOfficeSalesSummary/BoxOfficeSalesSummary.js, src/components/pages/admin/reports/boxOfficeSalesSummary/OperatorTable.js, src/components/pages/admin/reports/boxOfficeSalesSummary/TableRow.js
https://app.asana.com/0/1138868228851596/1132088822459437
Using smaller font size for exported PDFs so it doesn't cut off the date field.
[Box office sales summary.pdf](https://github.com/big-neon/bn-web/files/3749952/Box.office.sales.summary.pdf)
* No change
=> Boxoffice report pdf font fix

src/components/pages/admin/reports/settlement/SettlementReport.js
https://app.asana.com/0/1138868228851596/1132788783646657/f
Adds missing end date that'll appear after the API has been adjusted.
* No change
=> Using event_end when it's added to the api

src/components/pages/admin/reports/boxOfficeSalesSummary/BoxOfficeSalesSummary.js, src/components/pages/admin/reports/settlement/EventListTable.js, src/components/pages/admin/reports/settlement/SettlementReport.js
- Settlement report change event start to include time
- Remove event end date from settlement report
- Box office office sales report default date range to today
* No change
=> Report fixes 3

selenium/qa/docker-compose.yml, selenium/qa/extra/docker_scripts/start_hub_profile.sh, selenium/qa/extra/docker_scripts/start_local.sh, selenium/qa/local.Dockerfile, selenium/qa/src/test/java/config/HubRemoteDriverManager.java, selenium/qa/src/test/resources/conf/hub/chrome.suite.conf.json, selenium/qa/src/test/resources/conf/hub/firefox.suite.conf.json
maven command for test execution is located in start_.... .sh file.
Two different commands are(files) are needed to because when executing test on both chrome and firefox maven profile -P hub is used, that uses` /config.hub.testng.xml` suite file
And if we want to execute just one browser no profile is needed and `/config/local/testng.xml` file is used.
That is why there are three docker-compose services:
- one for testing on both browsers, where some test are run in parallel. `docker-compose up --build test`
- on firefox , `docker-compose up --build test-firefox`
- on chrome ,` docker-compose up --build test-chrome`
Each of mentioned servces  uses HubRemoteDriverManger class
* No change
=> automated test, docker execution

src/components/pages/admin/reports/eventAudit/Audit.js, src/components/pages/admin/reports/eventSummary/EventSummary.js, src/stores/reports/summaryReport.js, src/stores/reports/ticketCountReport.js
https://app.asana.com/0/1145151428687738/1145455742825753
See https://github.com/big-neon/bn-api/pull/1568
Let me know if this isn't an ideal way to accomplish this. Modified the API to return separate sales rows per client fee as it's grouped on that now. This allows the frontend to either group by sales as it was doing previously or by sales and the fee to further break out the data.
See example in PR https://github.com/big-neon/bn-api/pull/1568
* No change
https://github.com/big-neon/bn-api/pull/1568
=> Event summary report fee fix

src/components/pages/admin/fans/FanHistoryActivityCard.js
https://app.asana.com/0/1145151428687738/1126136784275287
It looks like the transfer activity cards are always using the 'status' of the transfer. This is the current status of it to allow for things like rendering a 'Cancel' button or the like. There's a separate 'action' which includes one of 'Started', 'Accepted', or 'Cancelled' which indicates the action involved that triggered the activity card. This PR is just to change to use that where possible for the rendering.
Noticed the issue while handling the associated API PR. Pushing up a fix here since it seems straightforward.
Without fixes:
With fixes:
Individual cards:
* No change
https://github.com/big-neon/bn-api/pull/1572 related but not required
=> Fix transfer activities to show action involved instead of current status on cards

src/components/pages/admin/reports/settlement/AdjustmentsList.js, src/components/pages/admin/reports/settlement/SettlementReport.js, src/components/pages/admin/reports/settlement/SettlementReportList.js
https://app.asana.com/0/1149047845558135/1149907075826105
- Instead of displaying the created at date for a report, use the end date for the report range.
- Move end date one day back if required. i.e. Report range becomes Monday to Sunday
* No change
=> Using end date for report range instead of created at date

src/stores/eventUpdate.js
https://app.asana.com/0/1149047845558135/1142660275386601
Defaulting ticket purchase limit to 10 for ticket types
* No change
=> Defaulting ticket purchase limit to 10

src/components/pages/admin/events/dashboard/orders/order/RefundDialog.js
https://app.asana.com/0/1151234524692625/1151849037631602
it was noticed that the API was not returning a refund reason after making a refund with one. I spent a little time debugging and noticed that the issue was related to us not sending in a refund reason at all. It looks like it's related to the specific line of code being modified as it treats the refund reasons like they are a hash with a key versus an array of objects needing to be iterated over.
* No change
=> Fix refund reason form submit

src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js
https://app.asana.com/0/1151234524692625/1152880367597697
Price schedules were being sorted in the render causing them to jump and switch places without the user knowing. This change just sorts on the first time the price schedules are loaded.
* No change
=> Sort pricing on load instead of in render method

src/components/pages/admin/reports/ExportPDF.js, src/components/pages/admin/reports/boxOfficeSalesSummary/BoxOfficeSalesSummary.js, src/components/pages/admin/reports/eventSummaryAudit/SummaryAudit.js, src/components/pages/admin/reports/transactions/Transactions.js
https://app.asana.com/0/1151234524692625/1134088423791936
When user runs any Big Neon report by date/time (org-level or event-level) the PDF version of the report should reflect the date/times that the user has chosen. 
* No change
=> Keeping the date range in PDF exports for reports

src/helpers/analytics.js, src/stores/user.js
Rename the tracking url so that it doesn't have `analytics` in it. Some ad blockers have a regex to stop all analytics. 
Also expire the campaign tracking data after 24 hours. We've had times where the tracking data is stored for months, skewing the checkout and page view stats
* No change
=> Rename tracking url and expire old tracking data

src/components/elements/event/EventHeaderImage.js
https://app.asana.com/0/1156907105711882/1156291458656601
Added 20px Padding between event name (and supporting artists text) and details card.
Before: https://cl.ly/0bea67a3aaae
After: https://cl.ly/6b16d488d008
* No change
=> Add padding between event title and event image

src/components/pages/admin/events/dashboard/fanNotifications/sections/NotificationProgress.js
https://app.asana.com/0/1158142652422330/1160462791103763/f
The percentage for number of notifications opened, was not rounded off. Was asked to round off to the 10th place.
https://share.getcloudapp.com/5zuyNy52
* No change
=> Push call round off notifications opened number

src/components/pages/authentication/forms/LoginForm.js, src/helpers/reactNative.js
[Asana](https://app.asana.com/0/1141185905028320/1168967382452721/f)
After a successful login in web view tokens along with user data are sent to the mobile app so that the user would get logged in in the app at the same time.
* No change
=> Send login tokens to mobile

src/components/pages/authentication/social/FacebookButton.js
Sends tokens to mobile after successful login with facebook.
* No change
=> Send tokens to mobile on FB signup

src/components/pages/authentication/forms/SignupForm.js
Sends token to the app on successful sign up.
* No change
=> Send tokens to mobile on signup
