src/components/pages/admin/organizations/Create.js, src/components/pages/admin/organizations/View.js, src/components/pages/authentication/Login.js, src/components/pages/authentication/Signup.js, src/helpers/api.js, src/stores/user.js
Created a shared function for handling headers and the token to be used globally.
=> Using shared API function

src/components/pages/authentication/Login.js
bn-api was changed to this naming convention instead.
=> Renaming username to email

src/components/pages/admin/organizations/Create.js
…nization
First doing an API call to get the user ID. Then using that user ID to assign ownership of the organization.
=> Using email address to link user to new organization

src/components/pages/authentication/Login.js, src/stores/user.js
API changed the way it returns the token. Added default roles when it's missing until scopes are implemented.
=> Token API updates

src/components/pages/admin/organizations/Create.js, src/components/pages/authentication/Signup.js, src/stores/user.js
- Searching on email address when creating an organization
- Getting roles from API call instead of from the token
- Using 'email' instead of 'username' on signup API call
=> API changes

src/components/pages/authentication/social/FacebookButton.js, src/components/routes/Routes.js, src/stores/user.js
- Updated facebook auth to correct API path
- Auto check if a user is logged in every 5 min
=> Facebook auth url

package-lock.json, src/components/pages/authentication/social/FacebookButton.js
A simple fix. Field in returned JSON was `access_token` not `token`
=> `token` -> `access_token`

src/components/common/form/LocationInputGroup.js, src/components/pages/admin/organizations/Create.js, src/components/pages/admin/venues/Create.js
- Create org to get the ID
- Update org with all the other fields using that ID (Ideally API should accept all fields on create)
=> Admin can update org details

src/components/common/MenuContent.js, src/components/pages/admin/organizations/Create.js, src/components/pages/admin/organizations/View.js, src/components/pages/authentication/Login.js, src/components/pages/authentication/Signup.js, src/components/pages/authentication/social/FacebookButton.js, src/components/routes/Routes.js, src/stores/user.js
Works for Admin, should work when API is updated to allow OrgOwners to view their own organizations.
=> Org owner updating organization details

src/components/common/form/SelectGroup.js, src/components/pages/authentication/Login.js, src/components/styles/theme.js
- Additional padding for input fields
- Added default disabled select option when none exist
=> Styling changes

src/components/pages/admin/events/Update.js, src/components/routes/Routes.js
- Adjusted date format to what the API is looking for
- Update function for existing events
- Removed logging
=> Fixed date format for API

src/components/common/form/LocationInputGroup.js, src/components/pages/admin/events/Update.js, src/components/pages/admin/organizations/LinkVenuesCard.js, src/components/pages/admin/organizations/Update.js, src/components/pages/admin/venues/Update.js
- If you click on an organization there's a box at the bottom to link venues. UX could possibly be improved but right now it's just for Admin users.
- Renamed 'create' button to 'update' when it's updating an entry
=> Assign venues to organizations

src/components/pages/authentication/Login.js, src/components/pages/authentication/Signup.js, src/components/pages/authentication/social/FacebookButton.js, src/helpers/api.js, src/stores/user.js
- Function for using `refresh_token` to get a new `access_token`
- Renamed stored 'token' to 'access_token'
=> Function for refreshing a token.

.eslintrc, src/components/routes/Routes.js, src/stores/user.js
Was accidentally passing through access token instead of refresh token.
=> Refresh token fix

src/components/pages/authentication/Signup.js, src/components/pages/profile/Index.js, src/stores/user.js
Fixed in https://github.com/big-neon/bn-api/issues/80
=> Split `name` into `first_name` and `last_name`

src/components/pages/admin/organizations/Update.js, src/components/pages/admin/venues/Update.js
Fixed in so can remove unnecessary code https://github.com/big-neon/bn-db/pull/55
=> No longer need to update right after creating orgs and venues.

src/components/pages/admin/venues/Update.js
Needed to add the addressBlock prop to the LocationInputgroup
=> Fix issue #44

src/components/common/MenuContent.js, src/components/pages/landing/cards/Event.js, src/components/pages/landing/cards/Results.js
Still waitning on an api change to allow non signed in users to view
=> Viewing events from home page

src/components/common/MenuContent.js, src/components/pages/admin/artists/Artist.js, src/components/pages/admin/artists/List.js, src/components/pages/admin/events/Event.js, src/components/routes/Routes.js
Waiting on model updates to add the rest of the fields.
=> Adding, editing and listing of artists

src/components/common/form/InputGroup.js, src/components/pages/admin/artists/Artist.js, src/components/pages/admin/events/Event.js, src/components/pages/admin/organizations/Organization.js, src/components/pages/admin/venues/Venue.js, src/validators/index.js, src/validators/url.js
Updated whole layout according to design spec.
=> Missing artist fields

src/components/common/NotificationList.js, src/components/common/RightHeaderMenu.js
Fixes #33 
Created a generic notification list component.
=> Missing env variables notification list

src/components/pages/admin/artists/Artist.js, src/components/pages/admin/artists/List.js, src/components/pages/admin/events/Event.js, src/components/pages/admin/events/List.js, src/components/pages/admin/organizations/LinkVenuesCard.js, src/components/pages/admin/organizations/List.js, src/components/pages/admin/organizations/Organization.js, src/components/pages/admin/organizations/UpdateCard.js, src/components/pages/admin/venues/List.js, src/components/pages/admin/venues/Venue.js, src/components/pages/authentication/Login.js, src/components/pages/authentication/Signup.js, src/components/pages/authentication/social/FacebookButton.js, src/components/pages/landing/cards/Results.js
Fix for https://github.com/big-neon/bn-web/issues/64
=> Checking for error message API responses if exists

src/components/common/AuthenticateCheckDialog.js, src/components/common/Container.js, src/components/common/RightHeaderMenu.js, src/components/pages/authentication/Login.js, src/components/pages/authentication/Signup.js, src/components/pages/events/ViewEvent.js, src/components/routes/Routes.js
Using React router redirects instead of popup. More robust way to define if a route should be allowed or not.
=> Changed the way authorised/unauthorised routes works.

src/components/pages/admin/events/Event.js
Just adding an array of tickets to the event data.
This will need to be structured correctly for the API endpoints.
=> Add the ticket data to the save data

src/components/common/Container.js, src/components/common/MenuContent.js, src/components/pages/landing/cards/Results.js, src/components/pages/landing/cards/Search.js, src/helpers/changeUrlParam.js, src/stores/eventResults.js
- Uses mobx to handle state of event results
- URL params to keep search query so link can be shared
- Design updates
=> Search functionality

.eslintrc, src/components/common/form/InputGroup.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/PromoCodeDialog.js, src/components/pages/events/TicketSelection.js, src/components/pages/events/ViewEvent.js, src/components/pages/landing/cards/Results.js, src/components/pages/landing/cards/SearchResultEventCard.js, src/components/routes/Routes.js
Basic layout for checkout experience. Still waiting on API endpoints.
=> Checkout experience

src/components/common/form/SelectGroup.js, src/components/pages/landing/cards/Results.js, src/components/pages/landing/cards/ResultsRegionFilter.js, src/stores/eventResults.js, src/stores/user.js
Working but waiting for api change to test.
=> Filter by region#104

src/components/pages/admin/invites/Accept.js, src/components/pages/admin/invites/Decline.js, src/components/pages/admin/organizations/InviteUserCard.js, src/components/pages/authentication/Signup.js, src/components/routes/Routes.js, src/stores/user.js
Design can be updated at a later stage.
Closes #145
=> Invite accept/reject components added.

src/components/pages/admin/events/Event.js, src/components/pages/admin/events/List.js, src/components/pages/landing/cards/Results.js, src/stores/eventResults.js, src/stores/selectedEvent.js
=> Restructured event data retrieved from API

src/components/common/Button.js, src/components/common/MenuContent.js, src/components/pages/admin/artists/List.js, src/components/pages/admin/events/Event.js, src/components/pages/admin/events/List.js, src/components/pages/admin/venues/List.js
=> Org owner components#161

src/components/common/cart/CartHeaderLink.js, src/components/common/cart/CartMobileBottomBar.js, src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js, src/stores/cart.js, src/stores/selectedEvent.js
=> Loading ticket types into checkout and cart

src/components/pages/authentication/Container.js, src/components/pages/authentication/Login.js, src/components/pages/authentication/PasswordReset.js, src/components/pages/authentication/ResetPasswordModal.js, src/components/routes/Routes.js
=> Password reset#100

.eslintrc, .githooks/pre-commit, package.json, src/components/common/form/AddressBlock.js, src/components/pages/admin/events/Event.js, src/components/pages/admin/venues/Venue.js, src/components/pages/authentication/Login.js, src/components/pages/authentication/social/FacebookButton.js
- New eslint rule for forcing spaces between curly brackets
- Git pre-commit hook for validating eslint rules
- Fixed some formatting
=> Git hooks and eslint formatting

src/components/pages/profile/Index.js
Closes #141 
Using bigneon api to update a user's profile details
=> Profile update#141

src/components/common/Button.js, src/components/pages/admin/artists/Artist.js, src/components/pages/profile/Index.js, src/helpers/cloudinaryWidget.js
=> Artist image uploading#65

src/components/common/form/InputGroup.js, src/components/common/form/LocationInputGroup.js, src/components/pages/admin/organizations/Organization.js, src/components/pages/admin/organizations/UpdateCard.js, src/components/pages/admin/organizations/cards/FeeScheduleCard.js, src/components/pages/admin/organizations/cards/InviteUserCard.js, src/components/pages/admin/organizations/cards/LinkVenuesCard.js, src/components/pages/admin/organizations/cards/UpdateCard.js
=> Create fee schedule#91

.eslintrc, src/components/common/form/AddressBlock.js, src/components/pages/admin/events/CancelEventDialog.js, src/components/pages/admin/events/Event.js, src/components/pages/admin/organizations/cards/FeeScheduleCard.js, src/components/pages/admin/organizations/cards/UpdateCard.js, src/components/pages/admin/venues/List.js, src/components/pages/admin/venues/Venue.js, src/components/pages/authentication/social/FacebookButton.js, src/helpers/api.js, src/index.js, src/stores/eventResults.js
- Saving and viewing fee schedules (Can't update yet)
- Renamed API calls for updated bn-api-node
- Forcing double quotes across the board
- Deprecated warning when using api.js to encourage me to migrate everything to bn-api-node
=> Save fee schedule#187

src/components/pages/events/CheckoutSelection.js, src/stores/cart.js
=> Adding items to cart

src/components/pages/admin/organizations/Organization.js, src/components/pages/admin/organizations/cards/FeeScheduleCard.js, src/components/pages/admin/organizations/cards/LinkVenuesCard.js, src/components/pages/admin/organizations/cards/UpdateCard.js
=> Updating fee schedules#193

src/components/pages/admin/artists/Artist.js, src/components/pages/admin/venues/List.js, src/stores/user.js
=> Artist validation#195

src/components/common/MenuContent.js, src/components/common/form/InputGroup.js, src/components/pages/admin/organizations/cards/FeeScheduleCard.js
Closes #93 
Closes https://github.com/big-neon/bn-api-node/issues/11
=> Org owner view fee schedule#93

src/components/elements/Container.js, src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/List.js, src/components/pages/admin/fans/Index.js, src/components/pages/boxoffice/BottomCheckoutBar.js, src/components/pages/boxoffice/CheckoutDialog.js, src/components/pages/boxoffice/TicketRow.js, src/components/pages/boxoffice/TicketSales.js, src/components/routes/OnRouteChange.js, src/components/routes/Routes.js
=> Showing available tickets for purchase for box office

src/components/elements/menu/MenuContent.js
=> Showing correct org member menu instead of user menu

src/components/pages/admin/events/EventSummaryCard.js, src/components/pages/admin/events/List.js
=> Showing if an event is cancelled

src/components/pages/admin/organizations/cards/FeeScheduleCard.js, src/components/pages/boxoffice/sales/CheckoutDialog.js
=> Renamed min_price needs to min_price_in_cents

src/components/pages/authentication/Container.js
=> Fixed login/signup scrolling issue

src/stores/boxOffice.js
=> Box office caching current event ID fix

src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js, src/stores/cart.js
=> Hiding breakdown of cart fees

src/components/common/cart/CartMobileBottomBar.js
=> Hiding mobile cart link on redundant pages

src/components/pages/admin/reports/Index.js, src/components/routes/Routes.js
closes #636 
Empty reports tabs so we don't have a coming soon page
=> #636 setup events route with empty reports states

src/components/pages/admin/events/List.js, src/components/pages/development/ElementShowCase.js, src/components/routes/Routes.js
I also added a page to put the different elements `ElementsShowcase` for devs to easily find what elements look like. Feel free to delete that
=> Added Upcoming or past to events list

.editorconfig, env.sample, package-lock.json, package.json, src/components/common/Recaptcha.js, src/components/pages/authentication/forms/LoginForm.js, src/components/pages/authentication/forms/SignupForm.js
Closes #174 
Depends on https://github.com/big-neon/bn-api/pull/831
=> Recaptcha on signup and login pages

src/components/pages/admin/invites/Accept.js
=> Org invite login button

src/components/elements/PageHeading.js, src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/refunds/Refunds.js, src/components/routes/Routes.js
=> Remove refunds from promoters#1108

src/components/pages/admin/events/dashboard/holds/List.js, src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js
=> Add is_private to ticket types

src/components/common/SelectOptionDialog.js, src/components/common/menu/lists/Admin.js, src/components/common/menu/lists/MobileSwitchOrgMenuItem.js, src/components/common/menu/lists/OrgMember.js, src/components/common/menu/lists/OrgOwner.js, src/components/elements/header/CurrentOrganizationMenu.js, src/components/elements/menu/MenuItem.js
=> Menu option for selecting an org on mobile

src/components/common/form/SelectGroup.js, src/components/elements/event/EventHeaderImage.js, src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/updateSections/Details.js, src/components/pages/events/CheckoutSuccess.js, src/components/pages/events/EventSummaryGrid.js, src/components/pages/events/ViewEvent.js, src/components/widgets/EventQR.js, src/helpers/ageLimit.js
This is a stop-gap solution to the age limit custom option.
I landed up going with the dropdown, and a superstring (the same as holds) that you can click to enter a custom string. It's dirty and ugly but it works.
=> Age limit as string

src/components/elements/event/EventHeaderImage.js, src/components/pages/admin/events/updateSections/Details.js, src/helpers/ageLimit.js
Added pink link colour to super text
Fixed the 0 age bug issue
Fixed the PropType issue
=> Fix age limit 0 bug

src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/codes/CodeDialog.js, src/components/pages/admin/events/dashboard/codes/CodeRow.js, src/components/pages/admin/events/dashboard/codes/List.js, src/components/routes/Routes.js
Requires big-neon/bn-api#1168
Requires big-neon/bn-api-node#329
=> [DO NOT MERGE] Add discount codes

src/components/elements/event/EventResultCard.js, src/components/routes/Routes.js, src/helpers/cloudinaryWidget.js, src/helpers/optimizedImageUrl.js
Doing the js load check for cloudinary
=> Added a size parameter to cloudinaryImageOptimization

src/components/elements/Pagination.js, src/components/pages/admin/fans/Index.js, src/components/pages/admin/reports/transactions/Transactions.js
Closes #1301 
Should not go live without https://github.com/big-neon/bn-api/pull/1143
=> [DNM] Tx detail report pagination search

src/components/pages/admin/reports/Index.js, src/components/pages/admin/reports/transactions/Transactions.js
Connected to big-neon/bigneon#45
Depends on big-neon/bn-api#1184
The transaction details report now also pulls the first page by default.
=> Added promo code details to transaction details

src/components/common/form/DateTimePickerGroup.js, src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/codes/CodeDialog.js, src/components/pages/admin/events/dashboard/codes/List.js
Addressing the QA feedback in https://github.com/big-neon/bigneon/issues/45
=> Promo code polish

src/components/pages/admin/events/dashboard/codes/CodeDialog.js, src/components/pages/admin/events/dashboard/codes/List.js
Fix the following issues identified during QA for Promo codes:
- Max tickets per user now saving if value is cleared (thus should be saved as 0 for unlimited)
- The update dialogs were always for access codes (left out the DateTime fields for discount codes)
=> Fixes for Promo code QA bugs

src/components/pages/admin/reports/ReportDate.js, src/components/pages/admin/reports/transactions/Transactions.js, src/stores/selectedEvent.js
Closes https://github.com/big-neon/bigneon/issues/83
=> Tx report export fix

src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js
Adds the ability to create ticket types that start when sales end for another ticket type
Requires big-neon/bn-api#1175
=> Add tiered pricing admin

src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js
Added in the ability to save against a ticket type that has not yet been saved
Still missing: Validating required fields
=> Revert revert tiered pricing

src/components/pages/admin/events/dashboard/codes/CodeDialog.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/TicketSelection.js, src/stores/selectedEvent.js
Closes https://github.com/big-neon/bigneon/issues/87
Closes https://github.com/big-neon/bigneon/issues/86
- Added checkboxes in Ticket Type multi select for promo codes.
- A percentage discount is now shown as a percentage and not in dollar terms on the checkout select screen.
=> Promo codes interface improvements

src/components/elements/charts/TicketTypeSalesBarChart.js, src/components/pages/admin/events/EventSummaryCard.js, src/components/pages/admin/events/dashboard/Summary.js
Closes #1345 
Deducts the sold value of held tickets from the total.
* No change
This is how it is currently
I can also show the used and remaining amount like so
=> Only display the remaining held tickets

src/components/pages/admin/organizations/sections/Update.js, src/components/pages/admin/venues/Venue.js
Closes https://github.com/big-neon/bn-web/issues/1239
Expand location section on location error
* No change
=> extend places on validation error

src/components/elements/Dialog.js
Closes #1296
* overflow-y changed into auto for modal to make scroll appear only when needed
* No change
=> overflow-y changed into auto for modal

src/components/elements/ColorTag.js, src/components/elements/form/NumberSelect.js, src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/TicketSelection.js, src/stores/eventUpdate.js
Connected to big-neon/bigneon#88
Requires big-neon/bn-api#1200
Requires https://github.com/big-neon/bn-api-node/pull/337
See issue for more details
* No change
=> [Please merge] Change SoldOutBehavior to TicketTypeVisibility

src/components/pages/events/CheckoutSelection.js, src/stores/selectedEvent.js
Closes big-neon/bigneon#81
Default value was not assigned because of out-of-sync with store issue, added success callback and redone the quantity assigner, tested, works
* No changes
=> default quantity fix

src/components/pages/admin/events/dashboard/codes/List.js
Code to handle when a ticket type id that is cancelled is still linked to a code. Currently the page will crash
Related to https://github.com/big-neon/bigneon/issues/125
* No change
=> Exclude cancelled ticket types

src/components/common/menu/lists/Admin.js, src/components/pages/admin/regions/List.js, src/components/pages/admin/regions/RegionRow.js, src/components/routes/Routes.js
Closes #874
* Regions management added to admin section of web app, CRUD in place. Only thing missing in API is DELETE method, but it was implemented, thus it is commented out for the future implementation, should work if endpoint present. Tested on mocks and connected to API.
* No changes
=> page created and crud added

src/components/pages/admin/organizations/sections/OtherFees.js, src/stores/cart.js
Closes https://github.com/big-neon/bigneon/issues/64
1) Handle the newly added CreditCardFees order item type added in https://github.com/big-neon/bn-api/pull/1211 when calculating the service fees in the checkout screen.
2) Added an input field in the Organizations Admin > Other Fees screen to be able to change an organization's credit card fee
* No change
1) https://cl.ly/03017a6ef4d9
2) https://cl.ly/d425f54fb643
=> [DNM] Handle credit card fees in checkout screen and add to Org admin screen

public/index.html
=> Preload key requests

public/index.html, public/style.css
=> Add font-display to specify how fonts are shown before they are loaded

scripts/build_prod.sh
=> Fixed the sh if statement

src/components/pages/admin/events/updateSections/Details.js
Closes: #1389 
This pull request addresses the associated issue by defaulting a venue if only one is available for a given organization. This scenario can only occur if the public venues in the system are limited as public venues are accessible to all organizations.
* No change
=> Event Create: select venue if only one exists

src/components/pages/boxoffice/guests/GuestRow.js
Closes #1408
Fixed text overflow issue when user purchases large amount of tickets.
* No change
https://cl.ly/f05fd16b3d53/Image%2525202019-05-09%252520at%2525201.51.06%252520PM.png
=> Fixed text overflow 

config/webpack.config.prod.js, package-lock.json, package.json
=> Reduce moment filesize

src/stores/tickets.js
Issue [#127](https://github.com/big-neon/bigneon/issues/127)
* No change
=> fix with localized time

src/components/pages/admin/artists/Artist.js, src/components/pages/admin/artists/List.js, src/components/pages/admin/venues/Venue.js
Closes: #1474
This branch closes the associated issue by:
- Hiding the edit link for public artists (we may want to revert this after https://github.com/big-neon/bigneon/issues/171 but right now it errors out)
- Sets the organization id on the artist flow (this will be useful even if we do 171 above as we'll need to know which organization to create a artist child for in regards to the public artists)
- Fixes a typo with the venue validations
User logged in with access to two private events and a public event:
Can create artists:
Can edit artists:
Admins can still edit:
Other organization user can only see the public at first but subsequently adds one and can see it:
* No change
=> DNM - Org member created artists are private, hide edit link for public artists

scripts/build_prod.sh
=> Added an output variable for building a branch

.github/pull_request_template.md
References: #1495
Simple change to adjust the pull request template to use "References" in place of "Closes"
* No change
=> PR Template: Switch closes to references for QA flow

src/components/pages/admin/events/updateSections/Tickets.js
Fixes the ticket_type loading issue of a null reference
* No change
=> Check if there is a ticketStartTime before running moment

src/components/pages/admin/events/dashboard/Summary.js
big-neon/bigneon#166 
Just checking for days left 
* No change
=> Hid days left if days left are 0

src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/ViewEvent.js, src/helpers/analytics.js
References big-neon/bigneon#182
* No change
=> Add analytics for FB Pixel

src/components/pages/admin/events/dashboard/refunds/Refunds.js
Implemented pagination
* No change
=> Implemented pagination on the order management page

package-lock.json, package.json, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js, src/stores/selectedEvent.js
=> Deployment to 1.0.436

src/components/pages/admin/reports/transactions/TransactionDialog.js, src/components/pages/admin/reports/transactions/Transactions.js
=> Add credit card fee to transaction detail report

package-lock.json, package.json, src/components/common/form/DateTimePickerGroup.js, src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/updateSections/Details.js, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js
=> Deployment - contains bug fixes

src/components/pages/events/CheckoutSelection.js, src/stores/cart.js
Related to big-neon/bigneon#217
* No change
=> Fix FB Pixel data for InitiateCheckout

src/components/pages/admin/events/dashboard/refunds/Refunds.js
Removes additional client side filtering causing limited results.
* No change
=> Removed additional client side filtering

src/stores/selectedEvent.js
Order the artists on the event view page by rank
* No change
=> Artists order hotfix

src/stores/reports/ticketCountReport.js
=> In summary reports split hold by price

src/stores/reports/ticketCountReport.js
=> Group holds by ticket price in event summary

package-lock.json, package.json, src/components/pages/admin/events/dashboard/refunds/Refunds.js, src/components/pages/admin/events/updateSections/Details.js, src/components/pages/admin/marketing/cards/EmailCard.js, src/components/pages/admin/marketing/cards/IntegrationCard.js, src/stores/eventUpdate.js
=> Live deploy

src/components/pages/admin/reports/transactions/TransactionDialog.js
Connected to #1609
Deduct the discount value from the face value in the TDR dialog
* No change
=> Show the face value after discount in TDR dialog

src/components/elements/header/EventCallToActionAppBar.js, src/components/pages/admin/events/updateSections/Details.js
- Fix UTC time on call to action top bar for event view page.
- Set default event end time on event create.
* No change
=> Jason time fixes 874

src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/marketing/FBPixelDialog.js, src/components/pages/admin/events/updateSections/Details.js, src/components/pages/admin/marketing/cards/IntegrationCard.js
Related to #1614.
- Removed from event creation
- Added help link
- Added dialog
* No change
=> Moved Facebook Pixel ID Input

src/components/pages/admin/events/dashboard/marketing/FBPixelDialog.js
https://github.com/big-neon/bn-web/issues/1637
Changed copy from "Create" to "Update"
* No change
=> Facebook pixel ID button copy

src/components/pages/admin/fans/FanActivityTransferRow.js, src/components/pages/admin/fans/FanDetails.js, src/components/pages/admin/fans/FanHistoryActivityCard.js, src/components/routes/Routes.js
https://github.com/big-neon/bigneon/issues/177
Implemented changes/thing missing for qa
* No change
=> QA Feedback implemented for fan management 

src/components/pages/admin/fans/Index.js
#1635
Changed the date added to use first interaction, changed last order date to last interaction, sorting by last interaction
* No change
=> Changed date added and sorting by last interaction

src/components/pages/admin/organizations/sections/FeeSchedule.js
https://github.com/big-neon/bn-web/issues/1646
Forcing whole numbers when saving cents.
* No change
=> Removing accidental floating point issues for cents.

src/components/elements/venue/VenueHeaderImage.js, src/components/pages/venues/ViewVenue.js
Updates the venue view page. We're still not linking to it anywhere so users won't see it yet. Just want to close https://github.com/big-neon/bn-web/pull/1531 without losing just the updates to the venue page. 
* No change
=> Updated venue view

src/components/pages/admin/fans/FanDetails.js, src/components/pages/admin/fans/FanHistoryActivityCard.js, src/components/pages/admin/fans/FanHistoryEventCard.js
https://github.com/big-neon/bigneon/issues/177 and #1506
#1506 - sorted out purchase display re. promo/discount codes
https://github.com/big-neon/bigneon/issues/177 - added date/time to accepted/cancelled by
* No change
=> Sorted out purchase display, added occurred at to transfer accept/cancel

src/components/pages/admin/fans/FanHistoryActivityCard.js, src/components/pages/myevents/EventTicketsCard.js, src/components/pages/myevents/Index.js, src/components/pages/myevents/transfers/CancelTransferDialog.js
#1555
Checking for ticket count, updated wording
* No change
=> Update to Cancel Transfer dialog

src/components/pages/admin/fans/FanHistoryActivityCard.js
https://github.com/big-neon/bigneon/issues/177
Just put links in to orders 
* No change
https://cl.ly/44a12d99283f
=> Fan activity cards & buttons link to correct order

selenium/qa/config/parallel_suite.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/config/testng.xml, selenium/qa/src/test/java/config/BrowserStackStatusEnum.java, selenium/qa/src/test/java/config/BrowsersEnum.java, selenium/qa/src/test/java/config/ChromeDriverManager.java, selenium/qa/src/test/java/config/DriverFactory.java, selenium/qa/src/test/java/config/FirefoxDriverManager.java, selenium/qa/src/test/java/pages/AccountPage.java, selenium/qa/src/test/java/pages/BasePage.java, selenium/qa/src/test/java/pages/FacebookLoginPage.java, selenium/qa/src/test/java/pages/Header.java, selenium/qa/src/test/java/pages/HomePage.java, selenium/qa/src/test/java/pages/LoginPage.java, selenium/qa/src/test/java/pages/ResetPasswordPage.java, selenium/qa/src/test/java/pages/mailinator/MailinatorHomePage.java, selenium/qa/src/test/java/pages/mailinator/MailinatorInboxPage.java, selenium/qa/src/test/java/test/BaseSteps.java, selenium/qa/src/test/java/test/ForgotPasswordStepsIT.java, selenium/qa/src/test/java/test/LoginStepsIT.java, selenium/qa/src/test/java/test/LoginWithFacebookStepsIT.java, selenium/qa/src/test/java/test/SignUpStepsIT.java, selenium/qa/src/test/java/utils/Constants.java, selenium/qa/src/test/java/utils/MsgConstants.java, selenium/qa/src/test/resources/conf/suite.conf.json
task4 #1602 Automation forget password, and wrong credentials on login test.
When running forget password, it is run in sequential order and several refresh action are executed, to make sure (proper)mail reaches inbox (in this case mailinator service is used).
Added capability to send name of test method and test status(PASS, FAIL) to browserstack via their api https://www.browserstack.com/automate/rest-api.
* No change
=> Mihajlokolesar#1602 test4 forget password

src/components/pages/admin/events/dashboard/orders/order/Header.js
=> Fixed order total calc

src/components/pages/admin/fans/FanHistoryActivityCard.js
#1664 
Left a dollar sign in by accident. Removed it.
* No change
=> Removed dollar sign from refund items

src/components/pages/admin/fans/Index.js
#1672
Added in the search box
* No change
https://cl.ly/5ab7f67daed9
=> Added in search

src/components/pages/admin/fans/Index.js
#1672
Just made sure that the search bar still shows when it returns no results, so you can delete the search query.
* No change
=> Fixed the missing search bar on mobile

src/components/pages/admin/fans/FanHistoryActivityCard.js
#177
Just changed the links to old orders for now
* No change
=> Changed order path from fan acitvity

src/components/pages/admin/fans/FanActivityTransferRow.js, src/components/pages/admin/fans/FanHistoryActivityCard.js
#1509 
Just changed the spacing for the transfer row to accommodate the button (cancel transfer) a bit better.
* No change
-
=> Changed spacing to accommodate button better

src/components/pages/admin/fans/FanHistoryActivityCard.js
#1509
Just checking for null values
* No change
=> Checking Fans for null cancelled/accepted by

src/components/pages/admin/fans/FanDetails.js, src/components/pages/admin/fans/FanHistoryActivityCard.js
https://github.com/big-neon/bigneon/issues/226 and #1509
Used correct occurred_at date/time, changed the check for accepted/cancelled by
* No change
https://cl.ly/cd672eeecbe8
=> Fixed occured_at & changed the check for accepted_by/cancelled_by

src/components/pages/admin/fans/FanHistoryActivityCard.js
#1507 
Switched the names around - redeemed by / redeemed for
* No change
https://cl.ly/5771c57d209f
=> Swapped redeemed by / for on fan check-ins

src/components/pages/myevents/transfers/CancelTransferDialog.js
#1555 
Changed "Cancel transfer" to "Confirm" as per design.
* No change
https://cl.ly/bb9e26d4c8e2
=> Changed wording on cancel dialog button

src/components/pages/admin/reports/eventSummary/EventSummary.js, src/stores/reports/summaryReport.js, src/stores/reports/ticketCountReport.js
#1566 
Added row for the order fees.
* No change
https://cl.ly/fb1f642f10e2
=> Added order fees into event summary report

src/components/pages/admin/fans/FanDetails.js, src/components/pages/admin/fans/FanHistoryActivityCard.js, src/components/pages/admin/fans/FanHistoryEventCard.js
#1705 
Making sure that if you're on a door person's "fan" profile, you see their check-in activity as is, but if if they scanned someone else in, the card is slightly different, for clarificaiton
* No change
https://cl.ly/f85d627d30fa
=> Checking for doorperson's check-in item & made new 'card type' 

src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js
https://app.asana.com/0/1131887530977355/1133748191045204?utm_source=asana_email&utm_medium=organic_email&utm_campaign=invite_welcomeprod_button
Scrolls up a little, so it doesn't look like you've accidentally published
Instead of https://cl.ly/62f814771f37 you have https://cl.ly/cd11fe4bbf8c
* No change
=> Added a minor scroll upward when adding another ticket type

public/widgets/events.js
https://app.asana.com/0/1135145228458502/1132923928870440
Each piece of the date element (day, month, date, year, hour, minute, meridian) now has the ability for customization
* No change
=> Added classed span wrappers to dates and times in the widget

package-lock.json, package.json, src/components/pages/events/EventDescriptionBody.js
https://app.asana.com/0/1135145228458502/1133369952010278
Finds urls in description and converts them to links. I'm using linkifyjs to do the transformations: https://soapbox.github.io/linkifyjs/docs/linkify-react.html
Before:
After - with pink links:
* No change
=> Added LinkifyJs and used LinkifyReact to convert urls to links

src/components/pages/admin/events/updateSections/Details.js
https://app.asana.com/0/1135145228458502/1133934081471828
Hiding that option for now.
https://cl.ly/04fbf52587ee
* No change
=> Commented out 'add embedded media'

src/components/pages/admin/events/dashboard/codes/CodeRow.js, src/components/pages/admin/events/dashboard/codes/List.js
https://app.asana.com/0/1135145228458502/1133349072898525
Tweaked spacing on promo code list
https://cl.ly/9e1c5e62d6fa
* No change
=> Tweaked spacing on promo code list

src/components/pages/events/ViewEvent.js, src/stores/selectedEvent.js
https://app.asana.com/0/1135145228458502/1133349072898523
Checking if the end date is in the past as well as if there aren't any tickets. Also added in what what there for the TODO, but left it it in there because the api has to be checked
https://cl.ly/296cd00292b1
* No change
=> Disabled 'Purchase tickets' CTA if event is in the past/no tickets are available at all

src/components/pages/myevents/public/Tickets.js
=> Remove hardcoded ticket type

package-lock.json, src/components/pages/admin/fans/FanHistoryActivityCard.js
https://app.asana.com/0/1131887530977355/1103621478711594?utm_source=asana_email&utm_medium=organic_email&utm_campaign=invite_welcomeprod_button
Changed all order links to point to new order management
https://cl.ly/c4a7db98fba7
* No change
=> Changed path to point to new order management

src/components/common/cart/CartMobileBottomBar.js
https://app.asana.com/0/1135145228458502/1133349072898517
Fixes the mobile cart button for returning to the correct event
* No change
=> Fix the cart returning to events for mobile

src/components/pages/boxoffice/sales/PurchaseSuccessOptionsDialog.js
Requires big-neon/bn-api#1457
Requires big-neon/bn-api-node#385
* No change
=> Send box office checkin instructions

src/components/common/menu/lists/Guest.js, src/components/common/menu/lists/User.js, src/components/elements/SMSAppLinkDialog.js, src/components/elements/SMSLinkForm.js, src/components/pages/events/CheckoutSuccess.js, src/components/pages/myevents/EventTicketsCard.js, src/components/pages/myevents/Index.js, src/components/pages/myevents/MobileEventTicketRow.js, src/config/settings.js, src/stores/user.js
https://app.asana.com/0/1135145228458502/1134394009920713
https://app.asana.com/0/1135145228458502/1133349072898541
- Removes action options (show QR and transfer buttons) from My Events. 
- Optimises ticket view for mobile
* No change
=> My events removed actions

src/components/pages/boxoffice/guests/GuestRow.js
=> Updated to new order link

selenium/qa/config/local/ltestng.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/src/test/java/config/MailinatorEnum.java, selenium/qa/src/test/java/pages/AbstractBase.java, selenium/qa/src/test/java/pages/components/TransferTicketSenderMailFrame.java, selenium/qa/src/test/java/pages/components/dialogs/TransferCancelDialog.java, selenium/qa/src/test/java/pages/components/user/EventComponent.java, selenium/qa/src/test/java/pages/mailinator/MailinatorFactory.java, selenium/qa/src/test/java/pages/mailinator/MailinatorHomePage.java, selenium/qa/src/test/java/pages/mailinator/TransferTicketMailinatorPage.java, selenium/qa/src/test/java/pages/mailinator/inbox/MailinatorInboxPage.java, selenium/qa/src/test/java/pages/mailinator/inbox/ResetPasswordMailinatorPage.java, selenium/qa/src/test/java/pages/mailinator/inbox/TransferCancelMailinatorPage.java, selenium/qa/src/test/java/pages/user/MyEventsPage.java, selenium/qa/src/test/java/test/ForgotPasswordStepsIT.java, selenium/qa/src/test/java/test/PurchaseStepsIT.java, selenium/qa/src/test/java/test/PurchaseWithTicketChangeStepsIT.java, selenium/qa/src/test/java/test/TransferTicketCancelStepsIT.java, selenium/qa/src/test/java/test/TransferTicketStepsIT.java
event though transfer ticket functionality was removed from app, this test was written before that, just not merged. Idea is to keep this test in case this functionality is returned to app (so we don't have to write it from scratch). https://github.com/big-neon/bn-web/issues/1743#issuecomment-523325935
Also there is a fix of error that previous task created. in testng.xml files quotation mark is in wrong place (most likely created when doing some conflict resolutions). 
* No change
=> #1743 automation

src/components/pages/events/EventDescriptionBody.js, src/components/pages/events/ViewEvent.js
https://app.asana.com/0/1135145228458502/1133369952010278
Adds Linkify to mobile view
* No change
=> Added linkify to mobile view

package.json
=> Manual version bump

package-lock.json, package.json, src/components/Application.js, src/index.js
The pagerduty night that @mikethetike got to enjoy last night.
Uses helmet to place a `<meta name="robots" content="noindex"/>` on the root page on non-production environments to stop being indexed.
* No change
=> Add a robots noindex to non-production sites

package-lock.json, package.json, src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/reports/Index.js, src/components/pages/admin/reports/ReportDate.js, src/components/pages/admin/reports/eventSummary/EventSummary.js, src/components/pages/admin/reports/transactions/Transactions.js
=> Deployment

src/components/pages/admin/events/dashboard/codes/CodeDialog.js, src/components/pages/admin/events/dashboard/holds/HoldDialog.js, src/components/pages/admin/events/dashboard/holds/children/ChildDialog.js, src/components/pages/events/ViewEvent.js
=> Remove char limit label and show purchase ticket links. Hotfix

src/components/pages/admin/events/dashboard/orders/order/OrderItems.js
https://app.asana.com/0/1132902661423463/1140784147360377
* No change
=> Add check for menu display

src/components/pages/events/Meta.js
=> Fixed the meta tag timezones for google

src/components/pages/events/Meta.js
Include the timezone offset in the dates
* No change
=> Format the meta tag dates as ISO8601

src/components/pages/events/ViewEvent.js
https://app.asana.com/0/1136728345391137/1132078885915005?utm_source=asana_email&utm_medium=organic_email&utm_campaign=invite_welcomeprod_button
Just fixed footer padding, and replaced image with a smaller one
* No change
=> Removed padding under footer and tiny header img

src/components/elements/event/EventResultCard.js, src/components/elements/pagination/index.js, src/components/pages/landing/Hero.js, src/components/pages/landing/Index.js, src/components/pages/landing/cards/Results.js, src/stores/eventResults.js
https://app.asana.com/0/1136728345391137/1132078885915005?utm_source=asana_email&utm_medium=organic_email&utm_campaign=invite_welcomeprod_button
Fixed font issues and added pagination
* No change
=> New homepage issues

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js, src/components/pages/authentication/social/FacebookButton.js
Requires big-neon/bn-api#1487
Fixes code after the facebook link for creating events on Facebook.
* No change
=> More Facebook Review fixes

public/site/css/widget.css, public/widgets/events.js, src/components/elements/header/SearchToolBarInput.js
https://app.asana.com/0/1136728345391137/1133358710817424
Added a v1 injection to hide the fields. As well as v0 for when the new styles are added to the widget page.
* No change
=> Widget backwards compatibility

public/icons/search-pink.svg, src/components/elements/Button.js, src/components/elements/event/EventResultCard.js, src/components/elements/footers/LandingFooter.js, src/components/elements/header/LandingAppBar.js, src/components/elements/header/RightUserMenu.js, src/components/elements/header/SearchToolBarInput.js, src/components/pages/landing/Hero.js, src/components/pages/landing/Index.js, src/components/pages/landing/cards/Results.js, src/index.css
=> Homepage tweaks

src/components/elements/event/EventResultCard.js, src/components/elements/header/AppBar.js, src/components/elements/header/LandingAppBar.js, src/components/elements/header/RightUserMenu.js
Just added the search back, fixed a font size, mobi search better
https://cl.ly/d43777d13d49
* No change
=> Homepage - Put the search back, minor tweaks

src/components/elements/event/EventResultCard.js
Changed promo img back
* No change
=> Homepage Event card img

src/components/elements/event/EventResultCard.js
Used wrong prop, fixed now
* No change
=> Fixed venue name var

src/components/elements/event/EventResultCard.js, src/components/elements/header/SearchToolBarInput.js
https://cl.ly/f050d4ad4bbe
* No change
=> Ellipsis after 2 lines title - Homepage

src/components/elements/header/AppBar.js, src/components/elements/header/SearchToolBarInput.js
=> Fixed large close icon

src/components/elements/footers/LandingFooter.js
home page
had wrong links in footer
* No change
=> Put the correct links in for mobi web

package-lock.json, package.json, src/components/elements/footers/LandingFooter.js
=> Deploy 564

src/components/pages/admin/events/dashboard/orders/order/Index.js
=> Added a 2 minute timeout to orders/activity

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
=> Fixed isSubmitting for Facebook

src/components/pages/admin/reports/ExportPDF.js, src/components/pages/admin/reports/Index.js, src/components/pages/admin/reports/boxOfficeSalesSummary/BoxOfficeSalesSummary.js, src/components/pages/admin/reports/boxOfficeSalesSummary/GrandTotalTable.js, src/components/pages/admin/reports/boxOfficeSalesSummary/OperatorTable.js, src/components/pages/admin/reports/boxOfficeSalesSummary/TableRow.js, src/components/pages/admin/reports/counts/TicketCounts.js, src/components/pages/admin/reports/transactions/Transactions.js
https://app.asana.com/0/1138868228851596/1132088822459437
Box office sales summary report
https://cl.ly/4e1672947fec
* No change
Requires a merge and publish of https://github.com/big-neon/bn-api-node/pull/389
Requires api fix: https://github.com/big-neon/bn-api/pull/1505
=> Boxoffice report

package-lock.json, src/components/elements/form/RadioButton.js, src/components/pages/admin/events/updateSections/TicketType.js
https://app.asana.com/0/1138868228851596/1103621478711584
Updated layout for Mike.
* No change
=> Updated box office sales checkboxes

src/components/elements/event/EventHeaderImage.js
https://app.asana.com/0/1138868228851596/1138875272655979
Just a simple color adjustment
* No change
=> [DNM] Updated sub heading font color

src/components/elements/event/EventHeaderImage.js, src/components/pages/events/Meta.js
=> Switched meta and event title

src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/CheckoutSuccess.js
Making sure all the props get passed down
* No change
=> Meta for Events. Passed props

src/components/elements/event/EventResultCard.js, src/components/pages/admin/events/List.js, src/components/pages/events/ViewEvent.js, src/components/pages/myevents/EventTicketsCard.js, src/components/routes/OnRouteChange.js, src/components/routes/Routes.js
https://app.asana.com/0/1138868228851596/1129435029011417?utm_source=asana_email&utm_medium=organic_email&utm_campaign=invite_welcomeprod_button
Made sure all the places linking to used new url
* No change
=> Using tickets route. CHanged all instances of going to event

src/components/pages/admin/reports/boxOfficeSalesSummary/BoxOfficeSalesSummary.js, src/components/pages/admin/reports/boxOfficeSalesSummary/OperatorTable.js
=> Date format and layout update

src/components/pages/admin/reports/settlement/AdjustmentsList.js, src/components/pages/admin/reports/settlement/EventListTable.js, src/components/pages/admin/reports/settlement/GrandTotalsTable.js, src/components/pages/admin/reports/settlement/SettlementReport.js, src/components/pages/admin/reports/settlement/SettlementReportList.js, src/components/pages/admin/reports/settlement/SingleEventSettlement.js, src/helpers/splitByCamelCase.js
https://app.asana.com/0/1138868228851596/1132788783646657
Mostly layout and wording changes.
* No change
=> Settlement report fixes

src/components/pages/admin/reports/ExportPDF.js, src/components/pages/admin/reports/settlement/SettlementReport.js, src/components/pages/admin/reports/settlement/SingleEventSettlement.js
https://app.asana.com/0/1138868228851596/1132788783646657
Exports a settlement report to PDF
* No change
=> Settlement report pdf export

src/components/pages/events/Meta.js
Just removed timezone and description from meta description
* No change
=> Removed timezone and description from meta description

src/components/pages/landing/cards/AltEventResultCard.js, src/components/pages/landing/cards/AltResults.js, src/components/pages/landing/cities/Index.js, src/components/pages/landing/organizations/Index.js, src/components/pages/landing/venues/Index.js, src/helpers/stateToAbbr.js
https://app.asana.com/0/1138868228851596/1144006298035698
- Sub title on page (i.e. "Upcoming Events at Arcade Empire") should be an H2
- Remove @ sign before venue name - we'll be making this same change on the homepage in S5
- Make States appear as 2 letter abbreviation, not fully spelled out
- Remove price range entirely
- Remove colons after DATE, BEGINS, & ENDS
- Center the load more button under the right column of the page rather than the full width of the page
- Just as with the links on the homepage, these events should link to the new /tickets/[event] URL, not the old /events/[event] URL
* No change
=> QA Changes for SEO landing pages

selenium/qa/src/test/java/enums/SettlementType.java, selenium/qa/src/test/java/model/Organization.java, selenium/qa/src/test/java/model/organization/OtherFees.java, selenium/qa/src/test/java/pages/AbstractBase.java, selenium/qa/src/test/java/pages/admin/organizations/AdminOrganizationsPage.java, selenium/qa/src/test/java/pages/admin/organizations/CreateOrganizationPage.java, selenium/qa/src/test/java/pages/admin/organizations/EditOrganizationPage.java, selenium/qa/src/test/java/pages/components/admin/organization/AdminOrganizationComponent.java, selenium/qa/src/test/java/pages/components/admin/organization/settings/FeeScheeduleComponent.java, selenium/qa/src/test/java/pages/components/admin/organization/settings/OtherFeesComponent.java, selenium/qa/src/test/java/pages/interfaces/Visible.java, selenium/qa/src/test/java/test/CreateOrganizationStepsIT.java, selenium/qa/src/test/java/test/facade/OrganizationStepsFacade.java, selenium/qa/src/test/java/utils/AssertMessages.java, selenium/qa/src/test/java/utils/MsgConstants.java, selenium/qa/src/test/java/utils/ProjectUtils.java, selenium/qa/src/test/resources/conf/beta_test_data.json, selenium/qa/src/test/resources/conf/develop_test_data.json
#1863
Added steps for updating fees of an organization. Currently only "other fees" steps are implemented. 
* No change
=> Organization update, other fees

src/components/pages/admin/reports/boxOfficeSalesSummary/OperatorTable.js
https://app.asana.com/0/1138868228851596/1132088822459437
* No change
=> Allows for more space on PDF report for date

src/components/pages/admin/reports/settlement/SettlementReport.js, src/helpers/money.js
https://app.asana.com/0/1138868228851596/1132788783646657
* No change
=> CSV export for settlement report

src/components/pages/events/Meta.js
Updated the title on the purchase ticket steps too
* No change
=> Updated page title on checkout steps

src/components/pages/landing/cards/AltEventResultCard.js
https://app.asana.com/0/1138868228851596/1144006298035698
Missing state
* No change
=> Missing State on SEO landing page cards

src/components/pages/events/EventDescriptionBody.js, src/components/pages/events/ViewEvent.js
suggestion link goes to org landing 
* No change
=> [DNM] Waiting on slug - Changed link to go to org landing page 

src/components/pages/events/EventDescriptionBody.js
fixed typo: concert -> concerts
* No change
=> Fixed typo: concerts

src/components/pages/admin/events/updateSections/TicketType.js, src/components/pages/admin/events/updateSections/Tickets.js, src/stores/eventUpdate.js
=> Defaulting to true for all channels

src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js
https://app.asana.com/0/1138868228851596/1144006298035698
Make sure Organization is being passed down to check out steps
* No change
=> Make sure Organization is being passed down to check out steps

src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js
https://app.asana.com/0/1145151428687738/1146326344025953
Adds formatting to ticket selection page and checkout page.
* No change
=> Formatting event descriptions on all event view pages

src/components/routes/OnRouteChange.js
https://app.asana.com/0/1145151428687738/1146306064914073
Added footer back
* No change
=> Added footer back to /tickets route too HOT FIX

src/components/pages/authentication/MobileStripeAuth.js
Removing local storage for web view for mobile app
* No change
=> Removing local storage

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
Adds some labels to the Facebook Event create page for App Review
* No change
=> Add labels to FB page

src/components/pages/landing/cards/AltEventResultCard.js, src/components/pages/landing/cards/AltResults.js, src/components/pages/landing/cities/Index.js, src/components/pages/landing/organizations/Index.js, src/components/pages/landing/venues/Hero.js, src/components/pages/landing/venues/Index.js, src/components/routes/OnRouteChange.js
https://app.asana.com/0/1145151428687738/1145354347144173
Mobi Styling for the landing pages as well as minor tweaks
https://cl.ly/008cc46c439d
* No change
=>  Seo landing pages - mobi & tweaks

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
More error handling to get through the Facebook AppReview
* No change
=> Better error handling for facebook

src/components/pages/events/CheckoutSelection.js
https://app.asana.com/0/1145151428687738/1145255671338009
* No change
=> Check if a ticket is published before adding it to a cart automatically

src/components/routes/Routes.js
https://app.asana.com/0/1145151428687738/1147201842130899
Keeping the affiliate link query in with redirect
* No change
=> Keeping the affiliate link query in with redirect

package-lock.json, package.json, src/components/routes/Routes.js
https://app.asana.com/0/1145151428687738/1147201842130899
Keeping the affiliate link query in with redirect
* No change
=> Hot fix aff link

package.json
Changes version so I can see if prod updated
* No change
=> Hot fix version check

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
=> [Hotfix] Add custom address to Facebook Event Create 

package.json, src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
=> Facebook 5

selenium/qa/config/local/ltestng.xml, selenium/qa/config/parallel_suite.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/src/test/java/pages/AbstractBase.java, selenium/qa/src/test/java/pages/EventsPage.java, selenium/qa/src/test/java/pages/TicketsConfirmationPage.java, selenium/qa/src/test/java/pages/TicketsPage.java, selenium/qa/src/test/java/pages/components/Header.java, selenium/qa/src/test/java/pages/components/SearchAndSignInMainPageComponent.java, selenium/qa/src/test/java/test/RefundEntireOrderAndOrderFeeStepsIT.java, selenium/qa/src/test/java/test/RefundEntireOrderExcludingOrderFeeStepsIT.java, selenium/qa/src/test/java/test/RefundOnlyOrderFeeStepsIT.java, selenium/qa/src/test/java/test/RefundPartialCheckOrderFeeRefundDisabledStepsIT.java, selenium/qa/src/test/java/test/TemplateRefundFeeSteps.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java
Updated url on tickets page. 
Since load more button is on events page, to ensure that event is found, first search using search input field is done  and then selecting specific event
Fixed the name in ltestng.xml and moved some tests from parallel to sequential execution
add some checks if shopping basket is full for logged in user for refundOrderFee tests.
* No change
=> updates to automation test to follow ui changes

src/components/pages/admin/events/updateSections/Details.js
=> Removing validation on private access codes

src/components/pages/events/ViewEvent.js
https://app.asana.com/0/1145151428687738/1145637275155499
Added links to get back to city/venue landing pages
* No change
=> Added links to view event details

public/widget.html, public/widgets/events.js, src/components/pages/admin/marketing/cards/WidgetCard.js
https://app.asana.com/0/1145151428687738/1148268856819633
If the source or medium exist and are no blank they will be appended to the tickets url.
This also adjusts the widget to point to the tickets endpoint instead of the events endpoint
* No change
=> Add UTM source and medium to widget

src/components/pages/events/ViewEvent.js
https://app.asana.com/0/752538406785488/1147721630579737
Use `tickets` instead of `events` in the href
* No change
=> Event detail page using new tickets url

src/components/elements/event/EventResultCard.js, src/components/pages/admin/events/dashboard/orders/order/TicketCard.js, src/components/pages/events/CheckoutConfirmation.js, src/components/pages/events/CheckoutSelection.js, src/components/pages/events/ViewEvent.js, src/components/pages/landing/cards/Results.js, src/helpers/analytics.js
https://github.com/big-neon/bn-api/pull/1563
Store data analytics in Big Neon database 
* No change
=> Add Big Neon page view analytics

src/components/elements/Button.js, src/components/pages/events/CheckoutSuccess.js
https://app.asana.com/0/1145151428687738/1134385245609851
Changed from <Link/> to normal link
* No change
=> Link fix for purchase order

src/components/pages/landing/cards/Results.js
https://app.asana.com/0/1145151428687738/1148735280531417
Make sure it still shows 3 items on a smaller screen
* No change
=> Added extra breakpoint for md

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js, src/components/pages/authentication/social/FacebookButton.js
https://app.asana.com/0/1145151428687738/1148089470889867
Just hiding the fields once published and some font tweaks and mobi friendly
* No change
=> Hiding fields once published to fb, tweaks

src/components/pages/events/CheckoutSuccess.js, src/components/pages/events/PurchaseDetails.js, src/components/pages/events/SuccessHero.js, src/helpers/removeCountryFromAddress.js
https://app.asana.com/0/1145151428687738/1134385245609851
- Helper function for removing Country from address
- Removed Event name from ticket types
- Made sure we're checking for promo codes/discounts
https://cl.ly/7cec2d5e4e9c
https://cl.ly/e557622f82b0
* No change
=> Purchase Confirmation QA Tweaks

src/components/pages/admin/events/dashboard/Container.js
https://app.asana.com/0/1145151428687738/1149070236668457
Moved menu items from Tools to Marketing
https://cl.ly/b0ce6d45dd93
* No change
=> Moved affiliate link and pixel ID menu items to marketing

src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
https://app.asana.com/0/1145151428687738/1148089470889867
Made description required, removed pt 3 after publish
* No change
=> Required fields and hiding point 3 after publish

package-lock.json, package.json, src/components/elements/form/rich-editor/RichTextInputField.js, src/components/pages/admin/events/dashboard/Container.js, src/components/pages/admin/events/dashboard/announcements/ConfirmSendDialog.js, src/components/pages/admin/events/dashboard/announcements/EmailHistory.js, src/components/pages/admin/events/dashboard/announcements/Index.js, src/components/pages/admin/events/dashboard/announcements/NewAnnouncementCard.js, src/components/pages/admin/events/dashboard/announcements/PreviewSendDialog.js, src/components/pages/admin/events/dashboard/announcements/SentEmailCard.js, src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js, src/components/pages/admin/fans/FanHistoryActivityCard.js, src/components/pages/admin/reports/settlement/SettlementReport.js, src/components/pages/admin/reports/settlement/SingleEventSettlement.js, src/components/pages/events/CheckoutSuccess.js, src/components/pages/events/PurchaseDetails.js, src/components/pages/events/SuccessHero.js, src/components/routes/Routes.js, src/helpers/removeCountryFromAddress.js
=> Deploy to beta v1.0.647

src/components/pages/admin/events/dashboard/Container.js
https://app.asana.com/0/1145151428687738/1149070236668457
Put Announcements back in
* No change
=> Put Announcements back in

src/components/pages/events/CheckoutSuccess.js
https://app.asana.com/0/1145151428687738/1134385245609851
Fixed mobi and some tweaks - sans address fix
* No change
=> Purchase confirmation fixes

src/components/pages/admin/fans/CancelTransferDialog.js, src/components/pages/admin/fans/FanHistoryActivityCard.js
https://app.asana.com/0/1145151428687738/1145908242665242
New dialog component for admin users when cancelling a transfer
* No change
=> Custom dialog for cancelling a transfer as an admin

src/components/pages/admin/events/dashboard/announcements/Index.js
https://app.asana.com/0/1149047845558135/1144347047244073
Removing invalid number of recipients until we have a proper endpoint
* No change
=> Removing invalid number of recipients for now

selenium/qa/src/test/java/data/holders/reports/boxoffice/OperatorTableData.java, selenium/qa/src/test/java/data/holders/reports/boxoffice/OperatorTableRowData.java, selenium/qa/src/test/java/data/holders/reports/boxoffice/ReportsBoxOfficePageData.java, selenium/qa/src/test/java/enums/PaymentType.java, selenium/qa/src/test/java/model/Purchase.java, selenium/qa/src/test/java/pages/admin/orders/manage/OrdersManageAdminPage.java, selenium/qa/src/test/java/pages/admin/reports/ReportsBoxOfficeSalesPage.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/ManageOrderRow.java, selenium/qa/src/test/java/pages/components/admin/reports/boxoffice/OperatorTable.java, selenium/qa/src/test/java/pages/components/admin/reports/boxoffice/OperatorTableRow.java, selenium/qa/src/test/java/test/facade/AdminBoxOfficeFacade.java, selenium/qa/src/test/java/test/facade/AdminEventDashboardFacade.java, selenium/qa/src/test/java/test/facade/reports/AdminEventReportsFacade.java, selenium/qa/src/test/java/test/facade/reports/ReportsBoxOfficeFacade.java, selenium/qa/src/test/java/test/reports/ReportBoxOfficeStepsIT.java, selenium/qa/src/test/java/utils/DateRange.java
=> reports box office timezone and sub totals verifications

src/components/pages/events/ViewEvent.js
https://app.asana.com/0/1149047845558135/1150659194555993 (last comment)
Checking for city slug before showing link in case slug is null
* No change
=> Checking for city slug before showing link

src/components/pages/admin/events/dashboard/marketing/FacebookEvents.js
=> Add title to facebook

src/components/pages/events/CheckoutSuccess.js
https://app.asana.com/0/1149047845558135/1150091533901723
Purchase confirmation tweaks
* No change
=> Purchase confirmation tweaks

selenium/qa/src/test/java/data/holders/events/results/EventResultCardData.java, selenium/qa/src/test/java/model/User.java, selenium/qa/src/test/java/model/Venue.java, selenium/qa/src/test/java/pages/admin/venue/CreateVenuePage.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/ActivityItem.java, selenium/qa/src/test/java/pages/components/events/EventResultCardComponent.java, selenium/qa/src/test/java/pages/components/tickets/DownloadAppComponent.java, selenium/qa/src/test/java/pages/components/tickets/OrderDetailsComponent.java, selenium/qa/src/test/java/pages/tickets/TicketsSuccesPage.java, selenium/qa/src/test/java/test/OrderManagmentSearchForOrdersStepsIT.java, selenium/qa/src/test/java/test/PurchaseStepsIT.java, selenium/qa/src/test/java/test/PurchaseWithTicketChangeStepsIT.java, selenium/qa/src/test/java/test/TransferTicketCancelStepsIT.java, selenium/qa/src/test/java/test/TransferTicketStepsIT.java, selenium/qa/src/test/java/test/VenueStepsIT.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java, selenium/qa/src/test/java/test/facade/VenueStepsFacade.java, selenium/qa/src/test/java/test/facade/orders/order/OrderManageFacade.java, selenium/qa/src/test/java/test/reports/ReportBoxOfficeStepsIT.java, selenium/qa/src/test/java/test/setupTest/CreateFixtures.java, selenium/qa/src/test/java/utils/DataConstants.java, selenium/qa/src/test/java/utils/ProjectUtils.java, selenium/qa/src/test/java/utils/VenueFormater.java, selenium/qa/src/test/java/utils/formatter/VenueFormatter.java, selenium/qa/src/test/resources/conf/beta_test_data.json, selenium/qa/src/test/resources/conf/develop_test_data.json
=> Automation test: venue create/edit updates

src/components/elements/Button.js
=> HOTFIX - Added breakpoint for button padding

src/components/elements/Button.js
Added a smaller padding value MD down
* No change
=> Added breakpoint for button padding

src/components/elements/footers/LandingFooter.js
https://app.asana.com/0/1151234524692625/1151597545094275/f
https://share.getcloudapp.com/jkun1wA0
* No change
=> Footer partner link updates

package-lock.json, package.json, selenium/qa/src/test/java/data/holders/events/results/EventResultCardData.java, selenium/qa/src/test/java/model/User.java, selenium/qa/src/test/java/model/Venue.java, selenium/qa/src/test/java/pages/admin/venue/CreateVenuePage.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/ActivityItem.java, selenium/qa/src/test/java/pages/components/events/EventResultCardComponent.java, selenium/qa/src/test/java/pages/components/tickets/DownloadAppComponent.java, selenium/qa/src/test/java/pages/components/tickets/OrderDetailsComponent.java, selenium/qa/src/test/java/pages/tickets/TicketsSuccesPage.java, selenium/qa/src/test/java/test/OrderManagmentSearchForOrdersStepsIT.java, selenium/qa/src/test/java/test/PurchaseStepsIT.java, selenium/qa/src/test/java/test/PurchaseWithTicketChangeStepsIT.java, selenium/qa/src/test/java/test/TransferTicketCancelStepsIT.java, selenium/qa/src/test/java/test/TransferTicketStepsIT.java, selenium/qa/src/test/java/test/VenueStepsIT.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java, selenium/qa/src/test/java/test/facade/VenueStepsFacade.java, selenium/qa/src/test/java/test/facade/orders/order/OrderManageFacade.java, selenium/qa/src/test/java/test/reports/ReportBoxOfficeStepsIT.java, selenium/qa/src/test/java/test/setupTest/CreateFixtures.java, selenium/qa/src/test/java/utils/DataConstants.java, selenium/qa/src/test/java/utils/ProjectUtils.java, selenium/qa/src/test/java/utils/formatter/VenueFormatter.java, selenium/qa/src/test/resources/conf/beta_test_data.json, selenium/qa/src/test/resources/conf/develop_test_data.json, src/components/pages/admin/reports/counts/TicketCountEmailDialog.js, src/components/pages/events/CheckoutSuccess.js
=> Deploy 1.0.692

selenium/qa/src/test/java/model/Event.java, selenium/qa/src/test/java/model/Organization.java, selenium/qa/src/test/java/model/Venue.java, selenium/qa/src/test/java/pages/admin/venue/CreateVenuePage.java, selenium/qa/src/test/java/pages/admin/venue/ValidationVenueFields.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/ActivityItem.java, selenium/qa/src/test/java/pages/components/tickets/OrderDetailsComponent.java, selenium/qa/src/test/java/pages/tickets/TicketsSuccesPage.java, selenium/qa/src/test/java/test/EditEventInformationStepsIT.java, selenium/qa/src/test/java/test/VenueStepsIT.java, selenium/qa/src/test/java/test/facade/AdminEventStepsFacade.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java, selenium/qa/src/test/java/test/facade/VenueStepsFacade.java, selenium/qa/src/test/java/test/facade/orders/order/OrderManageFacade.java, selenium/qa/src/test/java/test/reports/ReportBoxOfficeStepsIT.java, selenium/qa/src/test/java/test/setupTest/CreateFixtures.java, selenium/qa/src/test/java/utils/AccessabilityUtil.java, selenium/qa/src/test/java/utils/DataConstants.java, selenium/qa/src/test/java/utils/ProjectUtils.java, selenium/qa/src/test/java/utils/formatter/VenueFormatter.java, selenium/qa/src/test/resources/conf/beta_test_data.json, selenium/qa/src/test/resources/conf/develop_test_data.json
#2050 
- steps for checking required fields on venue create/update fields. 
- update to json data files, using new fields that have name of some other object in json file, and than retreiving that object in the java code. to avoid code duplication. (e.g in event objects there are venue_ref and organization_ref, that contain the names(keys) of corresponding venue and organization objects) 
* No change
=> automation test venue required fields

selenium/qa/src/test/java/pages/admin/venue/CreateVenuePage.java, selenium/qa/src/test/java/pages/components/GenericDropDown.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/ActivityItem.java, selenium/qa/src/test/java/test/OrderManagmentSearchForOrdersStepsIT.java, selenium/qa/src/test/java/test/VenueStepsIT.java, selenium/qa/src/test/java/test/facade/VenueStepsFacade.java, selenium/qa/src/test/java/test/facade/orders/order/OrderManageFacade.java, selenium/qa/src/test/java/utils/AccessabilityUtil.java, selenium/qa/src/test/java/utils/ProjectUtils.java
#2053 and update to #1848 test
* No change
=> automated test: state is abbreviated to 2 letters

src/components/pages/admin/organizations/sections/Update.js, src/components/pages/admin/venues/Venue.js
https://app.asana.com/0/1149047845558135/1139671931484353/f
Was asked to do the same address updates from the venue create/update form, for the orginization form. Also asked to make the country field disabled for non super super admins.
https://share.getcloudapp.com/GGuAZ98r
* No change
=> Updates to Org create address fields

src/components/pages/admin/reports/transactions/TransactionDialog.js, src/components/pages/admin/reports/transactions/Transactions.js
https://app.asana.com/0/1151234524692625/1149404711927729
Updated with new fees values from api
https://cl.ly/8dfda9e65adc
* No change
=> Reports - TDR - Updated service fees

src/components/pages/admin/events/dashboard/orders/order/OrderItems.js
https://app.asana.com/0/1151234524692625/1141457038002265
* No change
https://github.com/big-neon/bn-api/pull/1638
https://github.com/big-neon/bn-api-node/pull/416
=> Resend confirmation email

src/components/pages/admin/events/EventUpdate.js
https://app.asana.com/0/1153926226800754/1155638611161881/f
Different timezone from SAST: https://share.getcloudapp.com/X6uDEbPR
Changing venues with different timezones: https://share.getcloudapp.com/YEudrPxq
* No change
=> Using timezone from venue for future date

selenium/qa/config/local/ltestng.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/src/test/java/config/MailinatorEnum.java, selenium/qa/src/test/java/model/AnnouncementMail.java, selenium/qa/src/test/java/pages/AbstractBase.java, selenium/qa/src/test/java/pages/admin/events/DashboardEventPage.java, selenium/qa/src/test/java/pages/admin/events/announcement/AnnouncementPage.java, selenium/qa/src/test/java/pages/components/dialogs/announcement/AnnouncementPreviewSendDialog.java, selenium/qa/src/test/java/pages/components/dialogs/announcement/AnnouncementSendMailDialog.java, selenium/qa/src/test/java/pages/components/dialogs/announcement/AnnouncementSendToBuyersDialog.java, selenium/qa/src/test/java/pages/components/mailframes/AnnouncementMailFrame.java, selenium/qa/src/test/java/pages/mailinator/MailinatorFactory.java, selenium/qa/src/test/java/pages/mailinator/inbox/AnnouncementMailinatorPage.java, selenium/qa/src/test/java/pages/mailinator/inbox/MailinatorInboxPage.java, selenium/qa/src/test/java/test/TemplateRefundFeeSteps.java, selenium/qa/src/test/java/test/announcement/EmailTicketToBuyersUsingAnnouncement.java, selenium/qa/src/test/java/test/announcement/EmailToTicketHoldersUsingAnnouncement.java, selenium/qa/src/test/java/test/facade/AdminEventDashboardFacade.java, selenium/qa/src/test/java/test/facade/AdminEventStepsFacade.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java, selenium/qa/src/test/java/test/facade/FacadeProvider.java, selenium/qa/src/test/java/test/facade/announcement/AnnouncementFacade.java, selenium/qa/src/test/java/test/facade/orders/order/OrderManageFacade.java, selenium/qa/src/test/java/utils/AccessabilityUtil.java, selenium/qa/src/test/java/utils/AssertMessages.java, selenium/qa/src/test/java/utils/DataConstants.java, selenium/qa/src/test/java/utils/formatter/VenueFormatter.java, selenium/qa/src/test/resources/conf/beta_test_data.json, selenium/qa/src/test/resources/conf/develop_test_data.json
=> automated test: email to ticket holders via announcement

src/stores/user.js
https://app.asana.com/0/1156907105711882/1156859350763505
Updated permissions to accommodate Org  Owner and Admin
Before: https://cl.ly/a0b01663adb3
After (Admin & Owner): https://cl.ly/042a6678fab0
* No change
=> Updated permissions to accommodate Org  Owner and Admin

src/components/pages/admin/events/dashboard/orders/Index.js
https://app.asana.com/0/1156907105711882/1153901645242353
Changed param field name
Before: https://cl.ly/0d31f699c23b
After: https://cl.ly/4e80d8b9eb22
* No change
=> Filter by promo codes fix

src/components/pages/admin/events/dashboard/summary/charts/PageViewsTable.js
=> Fixed sales source percentage

config/templates/netlify_redirects, package-lock.json, package.json, src/components/pages/admin/events/dashboard/Summary_V2.js, src/components/pages/admin/events/dashboard/summary/EventAtAGlanceCard.js, src/components/pages/admin/events/dashboard/summary/SalesSourceCard.js, src/components/pages/admin/events/dashboard/summary/TicketSalesCard.js, src/components/pages/admin/events/dashboard/summary/charts/PageViewsTable.js
=> Another Dashboard deploy

config/webpack.config.prod.js, package-lock.json, package.json
=> Merge 720 live

src/components/pages/admin/events/dashboard/summary/charts/PageViewsTable.js, src/components/pages/admin/events/dashboard/summary/charts/TicketSalesTooltip.js
=> Make start date greater than or equal to on Page Views

config/webpack.config.prod.js, package-lock.json, package.json, src/components/pages/admin/events/dashboard/summary/EventAtAGlanceCard.js, src/components/pages/admin/events/dashboard/summary/SalesSourceCard.js, src/components/pages/admin/events/dashboard/summary/TicketSalesCard.js, src/components/pages/admin/events/dashboard/summary/charts/PageViewsTable.js, src/components/pages/admin/events/dashboard/summary/charts/TicketSalesChart.js
=> Deploy Dashboard

config/webpack.config.prod.js, package-lock.json, package.json, src/components/pages/admin/events/dashboard/summary/EventAtAGlanceCard.js, src/components/pages/admin/events/dashboard/summary/SalesSourceCard.js, src/components/pages/admin/events/dashboard/summary/TicketSalesCard.js, src/components/pages/admin/events/dashboard/summary/charts/PageViewsTable.js, src/components/pages/admin/events/dashboard/summary/charts/TicketSalesChart.js
=> Dashboard deploy

package-lock.json, package.json, src/components/pages/admin/events/dashboard/summary/charts/PageViewsTable.js
Release
Updated menu and routes in anticipation for the release
* No change
=> Release dashboard 

src/components/pages/admin/events/dashboard/summary/charts/ActivityChart.js
Small bug fix for when there are multiple legend rows on the dashboard for redeemed tickets
* No change
=> Small fix for the bug when multiple Legend rows

src/components/pages/admin/events/dashboard/summary/EventAtAGlanceCard.js, src/components/pages/admin/events/dashboard/summary/charts/ActivityChart.js
=> Add check to bypass cache for charts during the event

src/components/common/cart/CheckoutForm.js
https://app.asana.com/0/1158142652422330/1153902490758723
Commented out extra icons
https://cl.ly/88f81e5e4d2c
* No change
=> Adjusted Big Neon Crypto Payment Options to correspond with accepted currencies in Globee

src/components/pages/admin/events/dashboard/Summary_V2.js, src/components/pages/admin/events/dashboard/summary/CollapseCard.js, src/components/pages/admin/events/dashboard/summary/SalesSourceCard.js, src/components/pages/admin/events/dashboard/summary/TicketSalesBreakdownCard.js, src/components/pages/admin/events/dashboard/summary/TicketSalesChartCard.js, src/components/pages/admin/events/dashboard/summary/charts/ActivityChart.js, src/components/pages/admin/events/dashboard/summary/charts/TicketSalesChart.js, src/components/pages/admin/events/dashboard/summary/charts/TicketSalesTooltip.js
https://app.asana.com/0/1158142652422330/1158672886624945/f
https://app.asana.com/0/1158142652422330/1158662203660027/f
https://share.getcloudapp.com/z8un9XOD (x-axis dates)
https://share.getcloudapp.com/GGuAbNWQ (chart rerender on collapse)
* No change
=> Updates for chart x axis and fix for chart re render collapse

selenium/qa/src/test/java/enums/EnvironmentEnum.java, selenium/qa/src/test/java/pages/AbstractBase.java, selenium/qa/src/test/java/pages/admin/events/announcement/AnnouncementPage.java, selenium/qa/src/test/java/pages/admin/orders/manage/OrdersManageAdminPage.java, selenium/qa/src/test/java/test/EditEventInformationStepsIT.java, selenium/qa/src/test/java/test/OrderManagmentSearchForOrdersStepsIT.java, selenium/qa/src/test/java/test/announcement/EmailTicketToBuyersUsingAnnouncement.java
=> update to automation tests, enabled basic http authentication on develop

src/components/pages/landing/slugs/rich-landing-description.css
Changed font name 
https://cl.ly/b62f3a7444ec
* No change
=> Style non html text on landing page

src/components/pages/landing/slugs/Index.js, src/components/pages/landing/slugs/rich-landing-description.css
=> Hotfix shan style non html text

src/components/pages/admin/events/List.js
https://app.asana.com/0/1158142652422330/1158621681115177
In the event listing: change the word 'Dashboard' to 'Events'
https://share.getcloudapp.com/llu4Gym4
* No change
=> Dashboard -> Events

src/components/pages/myevents/EventTicketsCard.js
https://app.asana.com/0/1158142652422330/1159031009583881
Changed 'View my tickets' text to 'View Order'
https://share.getcloudapp.com/d5ueKeZ5
* No change
=> View tickets -> View Order

src/components/pages/admin/events/dashboard/fanNotifications/Index.js
=> Initial state for isNotificationAfter

src/components/pages/admin/events/updateSections/TicketType.js, src/stores/eventUpdate.js
Making sure that the start date & time are correct
vid 1: https://share.getcloudapp.com/9ZuNbe1q
* No change
=> [dnm] Start date timezone issue

selenium/qa/config/local/ltestng.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/src/test/java/pages/admin/events/AdminEventsPage.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/tickets/OrderTicketsDetails.java, selenium/qa/src/test/java/pages/components/dialogs/IssueRefundDialog.java, selenium/qa/src/test/java/pages/components/dialogs/RefundOverrideDialog.java, selenium/qa/src/test/java/pages/components/dialogs/RefundSuccessfulDialog.java, selenium/qa/src/test/java/test/RefundEntireOrderAndOrderFeeStepsIT.java, selenium/qa/src/test/java/test/RefundEntireOrderExcludingOrderFeeStepsIT.java, selenium/qa/src/test/java/test/RefundOnlyOrderFeeStepsIT.java, selenium/qa/src/test/java/test/RefundPartialCheckOrderFeeRefundDisabledStepsIT.java, selenium/qa/src/test/java/test/facade/orders/order/OrderManageFacade.java, selenium/qa/src/test/java/test/refund/override/RefundOverrideEntireOrderWithOrderFees.java, selenium/qa/src/test/java/test/refund/override/RefundOverrideEntireOrderWithOutFees.java, selenium/qa/src/test/java/test/refund/override/RefundOverrideJustPerEventFeePerOrderStepsIT.java
#2178 and #2177 and #2185  and #2186 
* No change
=> automation test refund override

src/helpers/bigneon.js
I've been looking into the refresh token and noticed that after the initial login access token expires, every call to the API does a `refresh` call first:
Basically what it looks like was happening is that before any call to the server, the `client` in `bn-api-node` would have it's internal `access_token` and `refresh_token` overwritten from local storage. 
I've fixed this by writing the tokens back to local storage whenever the `client` would overwrite them, using `OnTokenRefresh`.
I'm not sure how this will affect different login/logout scenarios
* No change
=> [High Risk] Store the tokens after refresh

src/components/common/form/DateTimePickerGroup.js, src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/updateSections/Details.js
https://app.asana.com/0/1158142652422330/1162085816175371/f
When users adjust the event date and end dates, there is no realtime validation before submitting it to the api.
Event with sales: https://share.getcloudapp.com/E0uqdmv1
Event with no sales: https://share.getcloudapp.com/OAurE7e4
* No change
=> Event create date validations

src/components/routes/Routes.js, src/stores/user.js
Add the ability to login with a "magic" link if it contains a refresh token that is still valid. 
* No change
=> Add logic to login with a refresh token

.gitignore, selenium/qa/.env.sample, selenium/qa/docker-compose.yml, selenium/qa/pom.xml, selenium/qa/src/test/java/config/DriverFactory.java, selenium/qa/src/test/java/model/Venue.java, selenium/qa/src/test/java/pages/admin/organizations/CreateOrganizationPage.java, selenium/qa/src/test/resources/conf/develop_test_data.json
Getting the tests to run in docker-compose, moved the url to the scratchpad and added a .env file.
@mihajlokolesar the tests are failing when I do a standard run with `docker-compose up test-chrome-debug` please can you see why.
* No change
=> Fixing the create organization state field

selenium/qa/config/local/ltestng.xml, selenium/qa/docker-compose.yml, selenium/qa/pom.xml, selenium/qa/src/test/java/pages/AbstractBase.java, selenium/qa/src/test/java/pages/SignUpPage.java, selenium/qa/src/test/java/pages/admin/fans/AdminFanProfilePage.java, selenium/qa/src/test/java/pages/admin/venue/ValidationVenueFields.java, selenium/qa/src/test/java/pages/components/GenericDropDown.java, selenium/qa/src/test/java/pages/components/admin/events/EventSummaryComponent.java, selenium/qa/src/test/java/pages/components/dialogs/CancelEventDialog.java, selenium/qa/src/test/java/pages/components/dialogs/DialogContainerComponent.java, selenium/qa/src/test/java/pages/components/dialogs/RefundOverrideDialog.java, selenium/qa/src/test/java/pages/components/tickets/OrderDetailsComponent.java, selenium/qa/src/test/java/test/CancelEventStepsIT.java, selenium/qa/src/test/java/test/SignUpStepsIT.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java, selenium/qa/src/test/java/test/refund/override/RefundOverrideEntireOrderWithOutFees.java, selenium/qa/src/test/java/test/setupTest/CreateFixtures.java, selenium/qa/src/test/java/utils/AccessabilityUtil.java, selenium/qa/src/test/java/utils/ElementLocatorUtil.java, selenium/qa/src/test/java/utils/ProjectUtils.java, selenium/qa/src/test/java/utils/SeleniumUtils.java, selenium/qa/src/test/resources/conf/develop_test_data.json
Some updates to tests. Note: there are a few tests that are stil failing, for example validation of data after purchase, sent mail preview on announouncement page that are due because this options are not working on new scratch env. Also login via fb is not working. Also I noticed a couple more that are failing, but still investigating if it's because change of environment or the app change it self, or is it selenium issue. I will push new updates as soon as possible. 
* No change
=> updates to data, docker, tests

package-lock.json, package.json, selenium/qa/config/local/ltestng.xml, selenium/qa/config/sequential_suite.xml, selenium/qa/src/test/java/pages/admin/events/CreateEventPage.java, selenium/qa/src/test/java/pages/components/GenericDropDown.java, selenium/qa/src/test/java/pages/components/admin/events/EventSummaryComponent.java, selenium/qa/src/test/java/test/EditEventInformationStepsIT.java, selenium/qa/src/test/java/test/facade/AdminEventStepsFacade.java, selenium/qa/src/test/java/test/facade/EventStepsFacade.java, selenium/qa/src/test/java/test/facade/reports/ReportsBoxOfficeFacade.java, selenium/qa/src/test/java/test/pastdates/MoveEventDatesToPastStepsIT.java, selenium/qa/src/test/java/test/refund/override/RefundOverrideEntireOrderWithOutFees.java, selenium/qa/src/test/java/test/reports/ReportBoxOfficeStepsIT.java, selenium/qa/src/test/java/utils/AccessabilityUtil.java, selenium/qa/src/test/java/utils/MsgConstants.java, src/components/pages/admin/events/updateSections/Details.js
=> Deploy event create fix

src/components/common/form/SelectGroup.js, src/components/pages/admin/events/dashboard/fanNotifications/Index.js, src/components/pages/admin/events/dashboard/fanNotifications/sections/MainContent.js, src/components/pages/admin/events/dashboard/fanNotifications/sections/NotificationProgress.js, src/components/pages/admin/events/dashboard/fanNotifications/sections/ScheduleSelector.js
https://app.asana.com/0/1158142652422330/1160432025127014/f
Added event start and end dates before selecting a date. 
Wording has been updated in previous PR. 
Event start and end dates before selecting date: https://share.getcloudapp.com/E0uqqrpD
Wording past date schedule: https://share.getcloudapp.com/d5u00p7j
Wording future date schedule: https://share.getcloudapp.com/2NuBBj4P
* No change
=> Push call UX updates

src/components/elements/event/ReadMoreAdditionalInfo.js, src/components/pages/events/ViewEvent.js, src/components/pages/events/rich-event-description.css
https://app.asana.com/0/1158142652422330/1160311367475553/f
Issues seen where the event description was inconsistent when adding the Read more button. 
There was a Readmore component that is being used in the EventOverview so decided to use the same component which limits it to 184 characters.
https://share.getcloudapp.com/p9uKP5lN
* No change
=> [DNM] Event view mobile updates

src/components/pages/admin/events/dashboard/orders/order/OrderItems.js, src/components/pages/admin/events/dashboard/orders/order/TicketCard.js, src/stores/user.js
https://app.asana.com/0/1158142652422330/1166338122619049
Have hidden menu items, buttons, and checkboxes for everyone expect Admin/Super
https://share.getcloudapp.com/geu2m0z7
* No change
=> [DNM] Only show refund buttons and checkboxes for Admin/Super

src/components/pages/admin/events/dashboard/orders/order/OrderItems.js, src/components/pages/admin/events/dashboard/orders/order/TicketCard.js, src/stores/user.js
=> Hotfix refund permissions

src/components/pages/admin/reports/settlement/AdjustmentsList.js, src/components/pages/admin/reports/settlement/GrandTotalsTable.js, src/components/pages/admin/reports/settlement/SettlementReport.js
https://app.asana.com/0/1158142652422330/1164097677491900/f
The adjustment add and delete buttons didn't check the status of the settlement report i.e. Pending or Finalized.
Pending: Can add/remove adjustments
Finalized: Cannot add/remove adjustments
https://timo614adjustsettlementfinalizationtousejob.scratch.bigneon.com/admin/reports/settlement-list
* No change
=> Settlement report adjustment disable add remove

src/components/common/menu/lists/Admin.js, src/components/elements/Container.js, src/components/elements/announcements/Banner.js, src/components/pages/admin/announcements/DeleteAnnouncementDialog.js, src/components/pages/admin/announcements/Index.js, src/components/routes/Routes.js, src/stores/announcements.js
Reverts big-neon/bn-web#2244
It's reverts all the way down.
=> Revert "Revert "Announcement banner in Studio""

src/components/pages/boxoffice/guests/Index.js
=> Change the label for box office search

src/components/pages/admin/marketing/cards/IntegrationCard.js
=> Fixes the logic error for displaying google ads

src/components/common/menu/lists/Admin.js
https://app.asana.com/0/1158142652422330/1164837537760218
Moved announcement menu item below slugs on the left hand menu
https://share.getcloudapp.com/qGuoLbp7
* No change
=> Moved announcement menu item below slugs

selenium/qa/src/test/java/enums/EnvironmentEnum.java, selenium/qa/src/test/java/enums/EventStatus.java, selenium/qa/src/test/java/model/Event.java, selenium/qa/src/test/java/pages/admin/events/EventOverviewPage.java, selenium/qa/src/test/java/pages/admin/events/EventPage.java, selenium/qa/src/test/java/pages/components/admin/events/overview/EventOverviewTopComponent.java, selenium/qa/src/test/java/pages/components/admin/orders/manage/ActivityItem.java, selenium/qa/src/test/java/pages/components/tickets/OrderDetailsComponent.java, selenium/qa/src/test/java/test/event/overview/EventOverviewStepsIT.java, selenium/qa/src/test/java/test/facade/AdminEventStepsFacade.java, selenium/qa/src/test/java/test/facade/event/overview/EventOverviewFacade.java
=> Automation event overview #2266

src/components/common/TagsContainer.js, src/components/pages/admin/events/EventOverview/OverviewHeader.js, src/components/pages/admin/events/EventSummaryCard.js, src/components/pages/admin/events/EventUpdate.js, src/components/pages/admin/events/List.js, src/components/pages/admin/events/dashboard/Container.js
https://app.asana.com/0/1158142652422330/1166977214175657/f
The status for events in the admin section was not pulling in the `override_status` field from the API which is the manually added status.
https://share.getcloudapp.com/RBud2O6Q
* No change
=> Added checks for override_status from api

src/components/pages/authentication/MobileStripeAuth.js, src/components/routes/OnRouteChange.js, src/components/routes/Routes.js, src/helpers/reactNative.js
@valentinamackovic you need this PR to go in then we can continue with the messaging.
* No change
=> Use specific channels for the rn messages
